# Generated by Django 5.2.14 on 2026-05-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='执行顺序')),
                ('parameter_mapping', models.JSONField(blank=True, default=dict, verbose_name='参数映射配置')),
                ('skip_on_failure', models.BooleanField(default=False, verbose_name='失败时跳过后续步骤')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_steps', to='testcases.testcase', verbose_name='测试用例')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testsuites.testsuite', verbose_name='所属套件')),
            ],
            options={
                'verbose_name': '测试步骤',
                'verbose_name_plural': '测试步骤',
                'ordering': ['order'],
                'unique_together': {('suite', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StepParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100, verbose_name='参数名')),
                ('json_path', models.CharField(max_length=200, verbose_name='JSONPath表达式')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_params', to='testsuites.teststep', verbose_name='所属步骤')),
            ],
            options={
                'verbose_name': '步骤参数',
                'verbose_name_plural': '步骤参数',
                'unique_together': {('step', 'param_name')},
            },
        ),
    ]
