# Generated by Django 5.2.14 on 2026-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teststep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='test_case',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='test_cases',
            field=models.JSONField(default=list, verbose_name='测试用例ID列表'),
        ),
        migrations.DeleteModel(
            name='StepParameter',
        ),
        migrations.DeleteModel(
            name='TestStep',
        ),
    ]
