# Generated by Django 5.2.14 on 2026-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuites', '0002_alter_teststep_unique_together_remove_teststep_suite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='suite_vars',
            field=models.JSONField(blank=True, default=dict, verbose_name='套件变量汇总'),
        ),
    ]
