# Generated by Django 4.2.7 on 2026-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuites', '0003_testsuite_suite_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='execution_count',
            field=models.IntegerField(default=0, verbose_name='执行次数'),
        ),
    ]
