# Generated by Django 4.2.7 on 2026-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuites', '0004_add_execution_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='web_test_cases',
            field=models.JSONField(blank=True, default=list, verbose_name='Web测试用例ID列表'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_cases',
            field=models.JSONField(default=list, verbose_name='API测试用例ID列表'),
        ),
    ]
