# Generated by Django 4.2.7 on 2026-07-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuites', '0006_add_perf_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='perf_config',
            field=models.JSONField(blank=True, default=dict, help_text='{case_id: {"users": 20, "duration": 120}}，覆盖性能用例的默认并发和持续时间', verbose_name='性能用例执行参数'),
        ),
    ]
