# Generated by Django 5.2.14 on 2026-05-16 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('test_cases', models.JSONField(default=list, verbose_name='测试用例ID列表')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_count', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('execution_log', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('allure_report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Allure报告路径')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '测试执行记录',
                'verbose_name_plural': '测试执行记录',
                'db_table': 'test_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
