# Generated by Django 5.2.14 on 2026-05-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('testsuites', '0002_alter_teststep_unique_together_remove_teststep_suite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='执行耗时(秒)'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='environment',
            field=models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('prod', '生产环境')], default='dev', max_length=10, verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='execution_results',
            field=models.JSONField(blank=True, default=list, verbose_name='用例执行结果详情'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='testsuites.testsuite', verbose_name='关联套件'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='trigger_type',
            field=models.CharField(choices=[('manual_suite', '套件执行'), ('manual_case', '用例执行'), ('debug', '调试模式'), ('scheduled', '定时任务'), ('ci', 'CI/CD')], default='manual_suite', max_length=20, verbose_name='触发方式'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='执行名称'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('partial', '部分通过')], default='pending', max_length=10, verbose_name='状态'),
        ),
    ]
