# Generated by Django 4.2.7 on 2026-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_add_suite_and_meta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='定时任务: 设定何时自动执行', null=True, verbose_name='计划执行时间'),
        ),
    ]
