# Generated by Django 4.2.7 on 2026-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_add_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='locked',
            field=models.BooleanField(default=False, help_text='锁定后不可修改或取消定时任务', verbose_name='已锁定'),
        ),
    ]
