# Generated by Django 4.2.7 on 2026-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_add_web_test_cases_to_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='test_cases',
            field=models.JSONField(default=list, verbose_name='API测试用例ID列表'),
        ),
    ]
