# Generated by Django 4.2.7 on 2026-07-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_add_web_test_cases_to_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='perf_test_cases',
            field=models.JSONField(blank=True, default=list, verbose_name='性能测试用例ID列表'),
        ),
    ]
