# Generated by Django 4.2.7 on 2026-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('tester', '测试工程师'), ('viewer', '查看者')], default='tester', help_text='用户角色：管理员拥有全部权限，测试工程师可操作自己的数据，查看者只读', max_length=20, verbose_name='角色'),
        ),
    ]
