# Generated by Django 4.2.7 on 2026-07-06 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('engine', models.CharField(choices=[('playwright', 'Playwright 精确模式'), ('ai', 'AI 模式 (midscene)')], default='playwright', help_text='Playwright精确控制 或 AI自然语言驱动', max_length=12, verbose_name='引擎')),
                ('target_url', models.CharField(max_length=500, verbose_name='目标URL')),
                ('browser_type', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit (Safari)')], default='chromium', max_length=10, verbose_name='浏览器类型')),
                ('headless', models.BooleanField(default=True, verbose_name='无头模式')),
                ('viewport', models.JSONField(blank=True, default=dict, help_text='如 {"width": 1280, "height": 720}', verbose_name='视口尺寸')),
                ('steps', models.JSONField(blank=True, default=list, help_text='[{"action": "navigate", "params": {"url": "..."}}, ...]', verbose_name='操作步骤')),
                ('ai_prompt', models.TextField(blank=True, default='', help_text='用自然语言描述测试步骤', verbose_name='AI 测试描述')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='断言规则')),
                ('screenshot_enabled', models.BooleanField(default=True, verbose_name='启用截图')),
                ('full_page_screenshot', models.BooleanField(default=False, verbose_name='全屏截图')),
                ('record_video', models.BooleanField(default=False, verbose_name='录屏')),
                ('priority', models.CharField(choices=[('P0', 'P0 - 最高'), ('P1', 'P1 - 高'), ('P2', 'P2 - 中'), ('P3', 'P3 - 低')], default='P2', max_length=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('inactive', '停用')], default='draft', max_length=10, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Web 测试用例',
                'verbose_name_plural': 'Web 测试用例',
                'db_table': 'web_test_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
