# Generated by Django 4.2.7 on 2026-07-06 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '异常')], max_length=10, verbose_name='执行状态')),
                ('duration', models.FloatField(default=0, verbose_name='执行耗时(秒)')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果详情')),
                ('screenshot', models.CharField(blank=True, default='', max_length=500, verbose_name='截图路径')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='web_testcases.webtestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'Web 测试执行记录',
                'verbose_name_plural': 'Web 测试执行记录',
                'db_table': 'web_test_executions',
                'ordering': ['-executed_at'],
            },
        ),
    ]
