# Generated by Django 4.2.7 on 2026-07-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_testcases', '0002_webtestexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtestcase',
            name='cookies',
            field=models.JSONField(blank=True, default=list, help_text='从浏览器复制的 cookie 数组，执行前自动注入。格式：[{"name":"sid","value":"xxx","domain":".doubao.com"}]', verbose_name='Cookie 注入'),
        ),
    ]
