# Generated by Django 4.2.7 on 2026-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_testcases', '0003_add_cookies_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtestexecution',
            name='status',
            field=models.CharField(choices=[('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '异常')], max_length=10, verbose_name='执行状态'),
        ),
    ]
