# Generated by Django 5.2.14 on 2026-05-16 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('api_endpoint', models.CharField(blank=True, default='', max_length=500, verbose_name='接口地址')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('expected_status_code', models.IntegerField(default=200, verbose_name='预期状态码')),
                ('expected_response', models.JSONField(blank=True, default=dict, verbose_name='预期响应')),
                ('assertions', models.TextField(blank=True, default='', verbose_name='断言说明')),
                ('priority', models.CharField(choices=[('P0', 'P0 - 最高'), ('P1', 'P1 - 高'), ('P2', 'P2 - 中'), ('P3', 'P3 - 低')], default='P2', max_length=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('inactive', '停用')], default='draft', max_length=10, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
