# Generated by Django 5.2.14 on 2026-05-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='assertion_rules',
            field=models.JSONField(blank=True, default=list, verbose_name='断言规则'),
        ),
    ]
