# Generated by Django 5.2.14 on 2026-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcase_assertion_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='extract_rules',
            field=models.JSONField(blank=True, default=list, verbose_name='变量提取规则'),
        ),
    ]
