# Generated by Django 6.0.5 on 2026-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcase_extract_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='context_vars',
            field=models.JSONField(blank=True, default=list, verbose_name='上下文变量'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='global_vars',
            field=models.JSONField(blank=True, default=list, verbose_name='全局变量'),
        ),
    ]
