# Generated by Django 4.2.7 on 2026-06-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_testcase_context_vars_testcase_global_vars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_status_code',
        ),
    ]
