# Generated by Django 5.2.14 on 2026-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='会话ID'),
        ),
    ]
