# Generated by Django 5.2.14 on 2026-06-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_chatmessage_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mode',
            field=models.CharField(choices=[('chat', '日常对话'), ('knowledge', '知识库问答')], db_index=True, default='knowledge', max_length=20, verbose_name='问答模式'),
        ),
    ]
