# Generated by Django 4.2.7 on 2026-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_chatmessage_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response_time',
            field=models.IntegerField(blank=True, default=0, help_text='从请求到完成的总耗时，单位毫秒', verbose_name='响应耗时(ms)'),
        ),
    ]
