# Generated by Django 5.2.14 on 2026-05-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='报告摘要')),
                ('report_html', models.TextField(blank=True, default='', verbose_name='HTML报告内容')),
                ('report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='报告文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='execution.testexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'test_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
