# Generated by Django 5.2.14 on 2026-06-02 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0004_testcase_context_vars_testcase_global_vars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='数据集名称')),
                ('dataset_type', models.CharField(choices=[('structured', '结构化数据'), ('llm_eval', 'LLM评测数据'), ('agent_dialog', 'Agent对话数据')], max_length=20, verbose_name='数据类型')),
                ('business_domain', models.CharField(blank=True, choices=[('order', '订单'), ('user', '用户'), ('logistics', '物流'), ('after_sales', '售后')], max_length=20, null=True, verbose_name='业务域')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('generation_config', models.JSONField(blank=True, default=dict, verbose_name='生成配置')),
                ('record_count', models.IntegerField(default=0, verbose_name='记录数')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('version', models.CharField(default='v1.0', max_length=20, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_factory.datafactorydataset', verbose_name='父数据集')),
            ],
            options={
                'verbose_name': '数据集',
                'db_table': 'data_factory_dataset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFactoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('order', '订单模板'), ('user', '用户模板'), ('logistics', '物流模板'), ('after_sales', '售后模板'), ('llm_prompt', 'LLM Prompt模板')], max_length=20, verbose_name='模板类型')),
                ('field_definitions', models.JSONField(default=list, verbose_name='字段定义')),
                ('generation_rules', models.JSONField(default=dict, verbose_name='生成规则')),
                ('prompt_template', models.TextField(blank=True, verbose_name='Prompt模板')),
                ('scope', models.CharField(choices=[('global', '全局共享'), ('team', '团队私有'), ('personal', '个人私有')], default='global', max_length=20, verbose_name='适用范围')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '造数模板',
                'db_table': 'data_factory_template',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='DataFactoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_content', models.JSONField(default=dict, verbose_name='数据内容')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=10, null=True, verbose_name='难度级别')),
                ('expected_output', models.JSONField(blank=True, default=dict, verbose_name='期望输出')),
                ('actual_output', models.JSONField(blank=True, default=dict, verbose_name='实际输出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='data_factory.datafactorydataset', verbose_name='所属数据集')),
            ],
            options={
                'verbose_name': '数据记录',
                'db_table': 'data_factory_record',
                'indexes': [models.Index(fields=['dataset', 'created_at'], name='data_factor_dataset_89d720_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataFactoryUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced_fields', models.JSONField(default=list, verbose_name='引用字段')),
                ('reference_type', models.CharField(choices=[('precondition', '前置条件'), ('request_param', '请求参数'), ('assertion', '断言数据')], max_length=20, verbose_name='引用类型')),
                ('referenced_at', models.DateTimeField(auto_now_add=True, verbose_name='引用时间')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_factory.datafactorydataset', verbose_name='被引用数据集')),
                ('referenced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='引用人')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase', verbose_name='引用用例')),
            ],
            options={
                'verbose_name': '引用日志',
                'db_table': 'data_factory_usage_log',
                'unique_together': {('dataset', 'testcase')},
            },
        ),
    ]
