# Generated by Django 5.2.14 on 2026-06-02 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactorydataset',
            name='change_log',
            field=models.TextField(blank=True, verbose_name='变更日志'),
        ),
        migrations.AddField(
            model_name='datafactorydataset',
            name='eval_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='评测配置'),
        ),
        migrations.AddField(
            model_name='datafactorydataset',
            name='linked_suites',
            field=models.JSONField(blank=True, default=list, verbose_name='关联套件'),
        ),
        migrations.AddField(
            model_name='datafactorydataset',
            name='sample_distribution',
            field=models.JSONField(blank=True, default=dict, verbose_name='样本分布'),
        ),
        migrations.CreateModel(
            name='PresetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('business_type', models.CharField(choices=[('order', '订单'), ('logistics', '物流'), ('after_sales', '售后'), ('merchant', '商家')], max_length=20, verbose_name='业务类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('field_definitions', models.JSONField(default=list, verbose_name='字段定义')),
                ('boundary_rules', models.JSONField(blank=True, default=dict, verbose_name='边界规则')),
                ('faker_mappings', models.JSONField(blank=True, default=dict, verbose_name='Faker映射')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '预置模板',
                'db_table': 'data_factory_preset_template',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='DataFactoryDatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='版本说明')),
                ('snapshot_config', models.JSONField(default=dict, verbose_name='配置快照')),
                ('snapshot_records_count', models.IntegerField(default=0, verbose_name='记录数快照')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='data_factory.datafactorydataset', verbose_name='所属数据集')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_factory.datafactorydatasetversion', verbose_name='父版本')),
            ],
            options={
                'verbose_name': '数据集版本',
                'db_table': 'data_factory_dataset_version',
                'ordering': ['-created_at'],
                'unique_together': {('dataset', 'version_number')},
            },
        ),
    ]
