# Generated by Django 5.2.14 on 2026-06-02 11:06

from django.db import migrations


def create_preset_templates(apps, schema_editor):
    """创建4套预置业务模板"""
    PresetTemplate = apps.get_model('data_factory', 'PresetTemplate')

    # 1. 订单模板
    PresetTemplate.objects.create(
        name='跨境电商订单数据',
        business_type='order',
        description='生成包含订单ID、金额、币种、商品信息的完整订单数据,支持边界值测试',
        field_definitions=[
            {'field': 'order_id', 'type': 'string', 'label': '订单ID', 'required': True, 'faker': 'uuid4'},
            {'field': 'customer_name', 'type': 'string', 'label': '客户姓名', 'required': True, 'faker': 'name'},
            {'field': 'amount', 'type': 'float', 'label': '订单金额', 'required': True, 'faker': 'random_float'},
            {'field': 'currency', 'type': 'string', 'label': '币种', 'required': True, 'faker': 'currency_code'},
            {'field': 'items_count', 'type': 'int', 'label': '商品数量', 'required': True, 'faker': 'random_int'},
            {'field': 'order_time', 'type': 'datetime', 'label': '下单时间', 'required': True, 'faker': 'date_time'},
            {'field': 'payment_method', 'type': 'string', 'label': '支付方式', 'required': False, 'faker': 'random_element'},
        ],
        boundary_rules={
            'amount': {
                'min': 0.01,
                'max': 999999.99,
                'boundary_values': [0, 0.01, -0.01, 999999.99, 1000000, None]
            },
            'items_count': {
                'min': 1,
                'max': 999,
                'boundary_values': [0, 1, -1, 999, 1000, None]
            },
            'currency': {
                'valid_values': ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'AUD', 'CAD'],
                'invalid_values': ['', 'XXX', '123', None]
            }
        },
        faker_mappings={
            'uuid4': 'faker.uuid4()',
            'name': 'faker.name()',
            'random_float': 'faker.pyfloat(min_value=0.01, max_value=999999.99, right_digits=2)',
            'currency_code': 'faker.currency_code()',
            'random_int': 'faker.random_int(min=1, max=999)',
            'date_time': 'faker.date_time_between(start_date="-1y", end_date="now")',
            'random_element': 'faker.random_element(elements=["credit_card", "paypal", "bank_transfer"])'
        },
        is_active=True,
        usage_count=0
    )

    # 2. 物流模板
    PresetTemplate.objects.create(
        name='国际物流追踪数据',
        business_type='logistics',
        description='生成物流单号、运输状态、轨迹信息等物流相关数据',
        field_definitions=[
            {'field': 'tracking_number', 'type': 'string', 'label': '物流单号', 'required': True, 'faker': 'tracking_number'},
            {'field': 'carrier', 'type': 'string', 'label': '承运商', 'required': True, 'faker': 'carrier'},
            {'field': 'origin_country', 'type': 'string', 'label': '起始国家', 'required': True, 'faker': 'country_code'},
            {'field': 'destination_country', 'type': 'string', 'label': '目的国家', 'required': True, 'faker': 'country_code'},
            {'field': 'status', 'type': 'string', 'label': '物流状态', 'required': True, 'faker': 'logistics_status'},
            {'field': 'estimated_delivery', 'type': 'date', 'label': '预计送达', 'required': False, 'faker': 'future_date'},
            {'field': 'weight_kg', 'type': 'float', 'label': '重量(kg)', 'required': True, 'faker': 'weight'},
        ],
        boundary_rules={
            'tracking_number': {
                'format': '^[A-Z]{2}[0-9]{9}[A-Z]{2}$',
                'invalid_formats': ['', '123', 'AB123456789', 'AB1234567890CD']
            },
            'weight_kg': {
                'min': 0.01,
                'max': 1000,
                'boundary_values': [0, 0.01, -0.01, 1000, 1000.01, None]
            },
            'status': {
                'valid_values': ['pending', 'picked_up', 'in_transit', 'customs_clearance', 'delivered', 'returned'],
                'invalid_values': ['', 'unknown', None]
            }
        },
        faker_mappings={
            'tracking_number': 'faker.bothify(text="??#########??", letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ")',
            'carrier': 'faker.random_element(elements=["DHL", "FedEx", "UPS", "China Post", "SF Express"])',
            'country_code': 'faker.country_code(representation="alpha-2")',
            'logistics_status': 'faker.random_element(elements=["pending", "picked_up", "in_transit", "customs_clearance", "delivered"])',
            'future_date': 'faker.future_date(end_date="+30d")',
            'weight': 'faker.pyfloat(min_value=0.01, max_value=1000, right_digits=2)'
        },
        is_active=True,
        usage_count=0
    )

    # 3. 售后模板
    PresetTemplate.objects.create(
        name='售后工单数据',
        business_type='after_sales',
        description='生成退款申请、退货工单、投诉记录等售后场景数据',
        field_definitions=[
            {'field': 'ticket_id', 'type': 'string', 'label': '工单ID', 'required': True, 'faker': 'uuid4'},
            {'field': 'order_id', 'type': 'string', 'label': '关联订单', 'required': True, 'faker': 'uuid4'},
            {'field': 'ticket_type', 'type': 'string', 'label': '工单类型', 'required': True, 'faker': 'ticket_type'},
            {'field': 'reason', 'type': 'string', 'label': '申请原因', 'required': True, 'faker': 'sentence'},
            {'field': 'refund_amount', 'type': 'float', 'label': '退款金额', 'required': False, 'faker': 'refund_amount'},
            {'field': 'priority', 'type': 'string', 'label': '优先级', 'required': True, 'faker': 'priority'},
            {'field': 'created_at', 'type': 'datetime', 'label': '创建时间', 'required': True, 'faker': 'date_time'},
        ],
        boundary_rules={
            'refund_amount': {
                'min': 0,
                'max': 999999.99,
                'boundary_values': [0, 0.01, -0.01, 999999.99, None],
                'validation': 'refund_amount <= order.amount'
            },
            'ticket_type': {
                'valid_values': ['refund', 'return', 'exchange', 'complaint', 'technical_support'],
                'invalid_values': ['', 'unknown', None]
            },
            'priority': {
                'valid_values': ['low', 'medium', 'high', 'urgent'],
                'invalid_values': ['', 'critical', None]
            }
        },
        faker_mappings={
            'uuid4': 'faker.uuid4()',
            'ticket_type': 'faker.random_element(elements=["refund", "return", "exchange", "complaint"])',
            'sentence': 'faker.sentence(nb_words=6)',
            'refund_amount': 'faker.pyfloat(min_value=0, max_value=999999.99, right_digits=2)',
            'priority': 'faker.random_element(elements=["low", "medium", "high", "urgent"])',
            'date_time': 'faker.date_time_between(start_date="-30d", end_date="now")'
        },
        is_active=True,
        usage_count=0
    )

    # 4. 商家模板
    PresetTemplate.objects.create(
        name='商家入驻信息',
        business_type='merchant',
        description='生成商家资质、店铺信息、联系方式等商家相关数据',
        field_definitions=[
            {'field': 'merchant_id', 'type': 'string', 'label': '商家ID', 'required': True, 'faker': 'uuid4'},
            {'field': 'shop_name', 'type': 'string', 'label': '店铺名称', 'required': True, 'faker': 'company'},
            {'field': 'business_license', 'type': 'string', 'label': '营业执照号', 'required': True, 'faker': 'license_number'},
            {'field': 'contact_email', 'type': 'string', 'label': '联系邮箱', 'required': True, 'faker': 'email'},
            {'field': 'contact_phone', 'type': 'string', 'label': '联系电话', 'required': True, 'faker': 'phone_number'},
            {'field': 'registration_date', 'type': 'date', 'label': '注册日期', 'required': True, 'faker': 'past_date'},
            {'field': 'rating', 'type': 'float', 'label': '店铺评分', 'required': False, 'faker': 'rating'},
        ],
        boundary_rules={
            'business_license': {
                'format': '^[0-9]{15,18}$',
                'invalid_formats': ['', '123', 'ABC', '12345678901234567890']
            },
            'contact_email': {
                'format': 'email',
                'invalid_values': ['', 'not_an_email', '@example.com', 'user@']
            },
            'rating': {
                'min': 0,
                'max': 5,
                'boundary_values': [0, 0.1, -0.1, 5, 5.1, None],
                'step': 0.1
            }
        },
        faker_mappings={
            'uuid4': 'faker.uuid4()',
            'company': 'faker.company()',
            'license_number': 'faker.bothify(text="###############")',
            'email': 'faker.email()',
            'phone_number': 'faker.phone_number()',
            'past_date': 'faker.date_between(start_date="-2y", end_date="today")',
            'rating': 'faker.pyfloat(min_value=0, max_value=5, right_digits=1)'
        },
        is_active=True,
        usage_count=0
    )


def reverse_seed_templates(apps, schema_editor):
    """回滚时删除预置模板"""
    PresetTemplate = apps.get_model('data_factory', 'PresetTemplate')
    PresetTemplate.objects.filter(
        business_type__in=['order', 'logistics', 'after_sales', 'merchant']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0002_datafactorydataset_change_log_and_more'),
    ]

    operations = [
        migrations.RunPython(create_preset_templates, reverse_seed_templates),
    ]
