# Generated by Django 5.2.14 on 2026-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0003_seed_preset_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactorydataset',
            name='purpose',
            field=models.CharField(blank=True, help_text='例如：618活动订单测试、跨境退货流程Agent评测等', max_length=500, verbose_name='用途说明'),
        ),
    ]
