# Generated by Django 4.2.7 on 2026-06-09 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='序号')),
                ('question', models.TextField(verbose_name='问题')),
                ('expected_answer', models.TextField(blank=True, default='', verbose_name='期望答案/关键词')),
                ('category', models.CharField(blank=True, default='general', help_text='general/knowledge/procedure/safety/boundary', max_length=50, verbose_name='问题分类')),
            ],
            options={
                'verbose_name': '测评问题',
                'verbose_name_plural': '测评问题',
                'db_table': 'eval_question',
                'ordering': ['task', 'index'],
            },
        ),
        migrations.CreateModel(
            name='EvalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('target_type', models.CharField(choices=[('knowledge_bot', '知识库问答机器人'), ('custom_api', '自定义API')], default='knowledge_bot', max_length=30, verbose_name='测评目标类型')),
                ('target_config', models.JSONField(default=dict, help_text='如API地址、知识库ID等', verbose_name='目标配置')),
                ('total_questions', models.IntegerField(default=0, verbose_name='问题总数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='回答正确数')),
                ('incorrect_count', models.IntegerField(default=0, verbose_name='回答错误数')),
                ('partial_count', models.IntegerField(default=0, verbose_name='部分正确数')),
                ('error_count', models.IntegerField(default=0, verbose_name='异常数')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='准确率(%)')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间(秒)')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='综合评分(0-100)')),
                ('security_issues_found', models.IntegerField(default=0, verbose_name='安全风险数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测评任务',
                'verbose_name_plural': '测评任务',
                'db_table': 'eval_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='问题文本')),
                ('expected_answer', models.TextField(blank=True, default='', verbose_name='期望答案')),
                ('actual_answer', models.TextField(blank=True, default='', verbose_name='实际回答')),
                ('category', models.CharField(blank=True, default='general', max_length=50, verbose_name='问题分类')),
                ('level', models.CharField(choices=[('correct', '✅ 正确'), ('incorrect', '❌ 错误'), ('partial', '⚠️ 部分正确'), ('error', '🔴 异常')], default='error', max_length=20, verbose_name='判定结果')),
                ('score', models.FloatField(default=0.0, verbose_name='得分(0-100)')),
                ('response_time', models.FloatField(default=0.0, verbose_name='响应时间(秒)')),
                ('ai_evaluation', models.TextField(blank=True, default='', verbose_name='AI评估说明')),
                ('has_security_risk', models.BooleanField(default=False, verbose_name='是否有安全风险')),
                ('security_risk_type', models.CharField(blank=True, default='', help_text='如: prompt_injection/data_leak/harmful_content', max_length=100, verbose_name='风险类型')),
                ('security_risk_detail', models.TextField(blank=True, default='', verbose_name='风险详情')),
                ('has_reference', models.BooleanField(default=False, verbose_name='是否有参考来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_evaluator.evalquestion', verbose_name='问题')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_evaluator.evaltask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '测评结果',
                'verbose_name_plural': '测评结果',
                'db_table': 'eval_result',
                'ordering': ['question__index'],
            },
        ),
        migrations.CreateModel(
            name='EvalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', verbose_name='总览摘要')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='准确率得分')),
                ('speed_score', models.FloatField(default=0.0, verbose_name='响应速度得分')),
                ('safety_score', models.FloatField(default=0.0, verbose_name='安全性得分')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='回答质量得分')),
                ('category_stats', models.JSONField(default=dict, verbose_name='分类统计')),
                ('score_distribution', models.JSONField(default=dict, verbose_name='分数分布')),
                ('response_time_stats', models.JSONField(default=dict, verbose_name='响应时间统计')),
                ('slow_questions', models.JSONField(default=list, verbose_name='响应慢的问题')),
                ('wrong_questions', models.JSONField(default=list, verbose_name='答错的问题')),
                ('risk_questions', models.JSONField(default=list, verbose_name='安全风险问题')),
                ('suggestions', models.JSONField(default=list, verbose_name='改进建议')),
                ('report_html', models.TextField(blank=True, default='', verbose_name='报告HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ai_evaluator.evaltask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '测评报告',
                'verbose_name_plural': '测评报告',
                'db_table': 'eval_report',
            },
        ),
        migrations.AddField(
            model_name='evalquestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_evaluator.evaltask', verbose_name='所属任务'),
        ),
    ]
