# Generated by Django 4.2.7 on 2026-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaltask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
