# Generated by Django 4.2.7 on 2026-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_evaluator', '0002_add_cancelled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('zhipu', '智谱 GLM'), ('qwen', '通义千问'), ('baidu', '百度文心'), ('other', '其他')], default='deepseek', max_length=20, verbose_name='提供商')),
                ('model_id', models.CharField(help_text='如 deepseek-chat, gpt-4o', max_length=100, verbose_name='模型ID')),
                ('api_url', models.URLField(verbose_name='API 地址')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, help_text='0-2，越低越确定性', verbose_name='温度')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'db_table': 'ai_model_config',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
