# Generated by Django 4.2.7 on 2026-07-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_evaluator', '0003_add_ai_model_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaltask',
            options={'ordering': ['-updated_at'], 'verbose_name': '测评任务', 'verbose_name_plural': '测评任务'},
        ),
    ]
