"""
沙箱模块单元测试

涵盖：
1. 正常执行
2. 超时 kill
3. 内存超限 kill
4. 子进程数超限
5. FileJail 文件隔离
6. 便捷函数 run_in_sandbox
7. Django 适配器 sandbox_run
"""
import os
import sys
import time
import tempfile
import unittest

# 确保可以导入 ai-orchestration-service 的模块
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.core.sandbox import (
    SandboxConfig,
    SandboxResult,
    SandboxStatus,
    SandboxExecutor,
    FileJail,
    ProcessManager,
    run_in_sandbox,
)


class TestFileJail(unittest.TestCase):
    """文件隔离测试"""

    def test_setup_and_cleanup(self):
        config = SandboxConfig(read_only_paths=[])
        jail = FileJail(config)

        work_dir = jail.setup()
        self.assertTrue(os.path.isdir(work_dir))
        self.assertIn("sandbox_", work_dir)

        jail.cleanup()
        self.assertFalse(os.path.exists(work_dir))

    def test_copy_read_only_file(self):
        """只读文件被拷贝到沙箱"""
        # 创建一个临时文件作为"只读文件"
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write("print('hello from read-only file')")
            ro_file = f.name

        try:
            config = SandboxConfig(read_only_paths=[ro_file])
            jail = FileJail(config)
            work_dir = jail.setup()

            copied = os.path.join(work_dir, os.path.basename(ro_file))
            self.assertTrue(os.path.isfile(copied))
            with open(copied, "r") as f:
                self.assertIn("hello from read-only file", f.read())

            jail.cleanup()
            self.assertFalse(os.path.exists(work_dir))
        finally:
            if os.path.exists(ro_file):
                os.unlink(ro_file)


class TestSandboxExecutor(unittest.TestCase):
    """沙箱执行器集成测试"""

    def test_normal_execution(self):
        """正常执行：exit_code=0"""
        result = run_in_sandbox(
            [sys.executable, "-c", "print('hello sandbox')"],
            timeout=10,
            max_memory_mb=256,
        )
        self.assertEqual(result.status, SandboxStatus.SUCCESS)
        self.assertEqual(result.exit_code, 0)
        self.assertIn("hello sandbox", result.stdout)
        self.assertGreater(result.duration_seconds, 0)

    def test_runtime_error(self):
        """运行时错误：exit_code≠0"""
        result = run_in_sandbox(
            [sys.executable, "-c", "raise SystemExit(1)"],
            timeout=10,
            max_memory_mb=256,
        )
        self.assertEqual(result.status, SandboxStatus.RUNTIME_ERROR)
        self.assertEqual(result.exit_code, 1)

    def test_timeout_kill(self):
        """超时被 kill"""
        # 死循环，2 秒后超时
        result = run_in_sandbox(
            [sys.executable, "-c", "import time; time.sleep(999)"],
            timeout=2,
            max_memory_mb=256,
        )
        self.assertEqual(result.status, SandboxStatus.TIMEOUT)
        self.assertAlmostEqual(result.duration_seconds, 2, delta=2)

    def test_memory_limit_kill(self):
        """内存超限被 kill"""
        # 分配 200MB 内存，限制 50MB
        code = "x = bytearray(200 * 1024 * 1024); import time; time.sleep(5)"
        result = run_in_sandbox(
            [sys.executable, "-c", code],
            timeout=10,
            max_memory_mb=50,
        )
        self.assertIn(
            result.status,
            [SandboxStatus.MEMORY_EXCEEDED, SandboxStatus.RUNTIME_ERROR],
            f"状态应为内存超限或运行时错误，实际: {result.status}",
        )
        # 注意：Windows 上内存超限检测有时不够快，脚本可能先 OOM 崩溃
        # 所以也接受 RUNTIME_ERROR（Python 自己 OOM 退出）

    def test_process_limit(self):
        """子进程数超限"""
        # fork 10 个子进程，限制最多 3 个
        code = (
            "import subprocess, time\n"
            "procs = [subprocess.Popen(['python', '-c', 'import time; time.sleep(5)']) "
            "for _ in range(10)]\n"
            "time.sleep(5)"
        )
        result = run_in_sandbox(
            [sys.executable, "-c", code],
            timeout=15,
            max_memory_mb=512,
            max_processes=3,
        )
        # 应该被 kill（进程数超限或超时）
        self.assertNotEqual(result.status, SandboxStatus.SUCCESS)

    def test_run_script_method(self):
        """SandboxExecutor.run_script() 方法"""
        executor = SandboxExecutor(SandboxConfig(timeout_seconds=10))
        result = executor.run_script(
            "print('generated by AI')\nprint('result: OK')",
            filename="ai_generated.py",
        )
        self.assertTrue(result.ok)
        self.assertIn("generated by AI", result.stdout)
        self.assertIn("result: OK", result.stdout)

    def test_cleanup_after_execution(self):
        """执行后临时目录被清理"""
        config = SandboxConfig(timeout_seconds=10, cleanup_after=True)
        executor = SandboxExecutor(config)

        # 先拿到临时目录路径
        work_dir = executor._jail.setup()
        temp_dir = executor._jail.temp_dir
        self.assertTrue(os.path.isdir(temp_dir))

        # 执行
        executor.run_command([sys.executable, "-c", "print('done')"])

        # 清理后不应存在
        self.assertFalse(os.path.exists(temp_dir))

    def test_result_to_dict(self):
        """SandboxResult.to_dict()"""
        result = run_in_sandbox(
            [sys.executable, "-c", "print('x' * 100)"],
            timeout=10,
        )
        d = result.to_dict()
        self.assertEqual(d["status"], "success")
        self.assertEqual(d["exit_code"], 0)
        self.assertIn("x" * 100, d["stdout"])

    def test_stdout_truncation(self):
        """stdout 过长时被截断"""
        result = run_in_sandbox(
            [sys.executable, "-c", "print('A' * 20000)"],
            timeout=10,
        )
        d = result.to_dict()
        self.assertLessEqual(len(d["stdout"]), 5000)


class TestConvenienceFunction(unittest.TestCase):
    """便捷函数测试"""

    def test_run_in_sandbox_defaults(self):
        """默认参数"""
        result = run_in_sandbox([sys.executable, "-c", "print(42)"])
        self.assertTrue(result.ok)
        self.assertIn("42", result.stdout)

    def test_run_in_sandbox_custom(self):
        """自定义参数"""
        result = run_in_sandbox(
            [sys.executable, "-c", "print('custom')"],
            timeout=5,
            max_memory_mb=128,
            read_only_paths=[],
        )
        self.assertTrue(result.ok)


if __name__ == "__main__":
    unittest.main(verbosity=2)
