# Generated by Django 4.2.7 on 2026-07-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('target_url', models.URLField(max_length=500, verbose_name='目标URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='例如 {"Content-Type": "application/json", "Authorization": "Bearer xxx"}', verbose_name='请求头')),
                ('body', models.JSONField(blank=True, help_text='POST/PUT 请求体，JSON 格式', null=True, verbose_name='请求体')),
                ('users', models.IntegerField(default=10, help_text='同时发压的虚拟用户数', verbose_name='并发用户数')),
                ('spawn_rate', models.IntegerField(default=1, help_text='用户启动速率，默认每秒启动1个', verbose_name='每秒启动用户数')),
                ('duration', models.IntegerField(default=60, help_text='压测持续时长', verbose_name='持续时间(秒)')),
                ('max_avg_response_time', models.IntegerField(default=1000, help_text='平均响应时间超过此值视为性能不达标', verbose_name='最大平均响应时间(ms)')),
                ('max_p95_response_time', models.IntegerField(default=2000, help_text='P95响应时间超过此值视为性能不达标', verbose_name='最大P95响应时间(ms)')),
                ('max_failure_rate', models.FloatField(default=0.01, help_text='请求失败率超过此值视为性能不达标，例如 0.01 = 1%', verbose_name='最大失败率')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=10, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '性能测试用例',
                'verbose_name_plural': '性能测试用例',
                'db_table': 'perf_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=10, verbose_name='状态')),
                ('users', models.IntegerField(verbose_name='并发用户数')),
                ('duration', models.IntegerField(verbose_name='持续时间(秒)')),
                ('total_requests', models.IntegerField(default=0, verbose_name='总请求数')),
                ('requests_per_second', models.FloatField(default=0, verbose_name='QPS')),
                ('failures', models.IntegerField(default=0, verbose_name='失败数')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间(ms)')),
                ('min_response_time', models.FloatField(default=0, verbose_name='最小响应时间(ms)')),
                ('max_response_time', models.FloatField(default=0, verbose_name='最大响应时间(ms)')),
                ('p50_response_time', models.FloatField(default=0, verbose_name='P50响应时间(ms)')),
                ('p90_response_time', models.FloatField(default=0, verbose_name='P90响应时间(ms)')),
                ('p95_response_time', models.FloatField(default=0, verbose_name='P95响应时间(ms)')),
                ('p99_response_time', models.FloatField(default=0, verbose_name='P99响应时间(ms)')),
                ('metrics_timeline', models.JSONField(blank=True, default=list, verbose_name='指标时间线')),
                ('thresholds_passed', models.BooleanField(default=True, verbose_name='阈值通过')),
                ('threshold_errors', models.JSONField(blank=True, default=list, verbose_name='阈值违规')),
                ('execution_log', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='performance.perftestcase', verbose_name='性能用例')),
            ],
            options={
                'verbose_name': '性能测试执行记录',
                'verbose_name_plural': '性能测试执行记录',
                'db_table': 'perf_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
