# Generated by Django 4.2.7 on 2026-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfexecution',
            name='exec_summary',
            field=models.JSONField(blank=True, default=dict, help_text='AI 诊断后的结构化总结，包含 score/summary/issues/recommendations', verbose_name='AI 执行总结'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='test_type',
            field=models.CharField(default='baseline', max_length=20, verbose_name='测试类型'),
        ),
        migrations.AddField(
            model_name='perftestcase',
            name='ramp_step_duration',
            field=models.IntegerField(default=30, help_text='梯度增压模式下，每个阶梯的持续时间', verbose_name='每步持续时间(秒)'),
        ),
        migrations.AddField(
            model_name='perftestcase',
            name='ramp_step_users',
            field=models.IntegerField(default=5, help_text='梯度增压模式下，每个阶梯增加的用户数', verbose_name='每步增加用户数'),
        ),
        migrations.AddField(
            model_name='perftestcase',
            name='test_type',
            field=models.CharField(choices=[('baseline', '基准测试'), ('ramp', '梯度增压'), ('mixed', '混合场景')], default='baseline', help_text='基准=固定并发 / 梯度=阶梯加压找拐点 / 混合=多接口权重配比', max_length=20, verbose_name='测试类型'),
        ),
    ]
