# Generated by Django 4.2.7 on 2026-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_add_mixed_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perftestcase',
            name='test_type',
            field=models.CharField(choices=[('baseline', '基准测试'), ('ramp', '阶梯递增'), ('spike', '尖峰测试'), ('stress', '压力测试'), ('mixed', '混合场景')], default='baseline', help_text='基准=固定并发 / 梯度=阶梯加压找拐点 / 混合=多接口权重配比', max_length=20, verbose_name='测试类型'),
        ),
    ]
