# Generated by Django 4.2.7 on 2026-07-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_add_perf_test_cases'),
        ('performance', '0004_add_mixed_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfexecution',
            name='suite_execution',
            field=models.ForeignKey(blank=True, help_text='当从测试套件中触发时，关联到套件执行记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_executions', to='execution.testexecution', verbose_name='所属套件执行'),
        ),
    ]
