# Generated by Django 4.2.7 on 2026-06-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('rule_type', models.CharField(help_text='completeness/format/content/duplicate', max_length=50, verbose_name='规则类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='规则描述')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('check_points', models.JSONField(default=list, verbose_name='检查点')),
                ('deduction_rules', models.JSONField(default=dict, verbose_name='扣分规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '质检标准',
                'verbose_name_plural': '质检标准',
                'db_table': 'quality_standard',
                'ordering': ['rule_type', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_cases', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='合格用例数')),
                ('warning_cases', models.IntegerField(default=0, verbose_name='警告用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='不合格用例数')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='综合评分')),
                ('check_duplicates', models.BooleanField(default=True, verbose_name='检查重复')),
                ('check_completeness', models.BooleanField(default=True, verbose_name='检查完整性')),
                ('check_format', models.BooleanField(default=True, verbose_name='检查格式规范')),
                ('check_content_quality', models.BooleanField(default=True, verbose_name='检查内容质量')),
                ('duplicate_threshold', models.FloatField(default=0.85, verbose_name='相似度阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '质检任务',
                'verbose_name_plural': '质检任务',
                'db_table': 'quality_check_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, default='', max_length=100, verbose_name='用例编号')),
                ('case_title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('case_content', models.JSONField(default=dict, verbose_name='用例内容')),
                ('score', models.FloatField(default=0.0, verbose_name='评分(0-100)')),
                ('level', models.CharField(default='warning', help_text='pass/warning/fail', max_length=20, verbose_name='等级')),
                ('completeness_score', models.FloatField(default=0.0, verbose_name='完整性得分')),
                ('format_score', models.FloatField(default=0.0, verbose_name='格式规范得分')),
                ('content_score', models.FloatField(default=0.0, verbose_name='内容质量得分')),
                ('issues', models.JSONField(default=list, verbose_name='问题列表')),
                ('suggestions', models.JSONField(default=list, verbose_name='优化建议')),
                ('duplicate_of', models.CharField(blank=True, default='', max_length=100, verbose_name='疑似重复于')),
                ('duplicate_similarity', models.FloatField(default=0.0, verbose_name='重复相似度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality_checker.qualitychecktask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '质检结果',
                'verbose_name_plural': '质检结果',
                'db_table': 'quality_check_result',
                'ordering': ['-score'],
            },
        ),
    ]
