# Generated by Django 4.2.7 on 2026-06-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitychecktask',
            name='pass_rate',
            field=models.FloatField(default=0.0, verbose_name='通过率(%)'),
        ),
        migrations.AddField(
            model_name='qualitychecktask',
            name='scenario',
            field=models.CharField(default='general', help_text='general-功能测试, api-接口测试', max_length=20, verbose_name='测试场景'),
        ),
    ]
