# LUTE 1000 递进式面试攻防题 - 第1章：AI测试平台项目深挖（Q1-Q120）
# 路特创新 AI算法测试工程师 专属
# 每道题包含 L1→L2→L3 完整追问链 + 兜底策略

def S(title):
    """章节标记 - 由生成器脚本处理"""
    pass

def Q(q, a):
    """题目 - 由生成器脚本收集到DATA列表"""
    pass

# ============================================================
# 第1章：你的AI测试平台项目深挖（Q1-Q120）
# ============================================================

S("第1章 你的AI测试平台项目深挖（Q1-Q120）")
S("  1.1 平台整体架构（Q1-Q20）")

Q("Q1.【L1开场】请介绍一下你做的AI测试平台。",
  "【你的L1回答】\n"
  "我做的是一个面向AI应用的自动化测试平台，核心能力包括三个方面：\n\n"
  "第一是Prompt评测模块。支持批量管理Prompt模板、版本控制（Prompt as Code）、自动化回归测试。我们把Prompt存在Git仓库里，每次变更都会触发CI流水线，用固定测试集跑一遍，对比新旧版本的准确率、相关性等指标，类似单元测试的思路。\n\n"
  "第二是RAG评测模块。针对检索增强生成场景，集成了RAGAS框架，评测Faithfulness（忠实度）、Answer Relevancy（答案相关性）、Context Precision（上下文精确度）和Context Recall（上下文召回率）四个核心指标。还做了可视化看板，用Grafana展示每次评测的趋势变化。\n\n"
  "第三是Agent测试模块。针对工具调用型Agent，我们设计了一套测试框架，能模拟不同的工具返回结果（正常、异常、超时、空结果），验证Agent的规划和执行是否正确。\n\n"
  "技术栈方面：后端用FastAPI + Celery做异步任务，前端Vue3 + Element Plus，数据库PostgreSQL，向量数据库用Milvus存储评测的embedding，部署用Docker Compose。\n\n"
  "【L2追问】\n"
  "你说后端用FastAPI，为什么不选Flask或者Django？你是怎么考虑的？\n\n"
  "【L2应对】\n"
  "这个选型我做过详细对比。Flask虽然轻量，但它是同步框架，AI调用（比如调OpenAI API）动辄几秒甚至几十秒，同步模式下会阻塞整个Worker，并发能力很差。虽然可以用Flask + gevent/eventlet打补丁，但那是'假异步'，本质上还是用协程模拟，遇到CPU密集任务就露馅了。\n\n"
  "Django太重了。它的ORM、中间件、模板引擎对我们这个API为主的平台来说是大炮打蚊子。而且Django的异步支持是3.1之后才加的，不够成熟。\n\n"
  "FastAPI是原生异步的，基于Starlette + Pydantic，所有请求处理都是async/await，不会阻塞事件循环。AI调用本身就是IO密集型，异步是最佳实践。另外FastAPI自动生成Swagger文档，前后端联调效率很高。Pydantic的类型校验也让接口参数校验非常方便，减少了很多if-else的判断代码。\n\n"
  "【L3追问】\n"
  "你说Flask + gevent是'假异步'，那FastAPI的async/await和gevent到底有什么区别？事件循环的底层机制有什么不同？\n\n"
  "【L3应对/兜底】\n"
  "这是一个很好的问题。gevent的协程是基于Greenlet的，它在用户态做上下文切换，通过monkey patch把标准库的阻塞IO替换成非阻塞版本。但问题是，如果有一个CPU密集型操作（比如大JSON的序列化），gevent无法让出控制权，会阻塞整个进程。\n\n"
  "FastAPI底层的asyncio是基于操作系统的事件循环（Linux上是epoll，Mac上是kqueue），当遇到await一个IO操作时，Python解释器会真正地把控制权交还给事件循环，让其他协程运行。这比gevent更可靠，因为它是语言级别支持的，不需要monkey patch。\n\n"
  "但说实话，如果要我深入解释asyncio的Task、Future和coroutine在CPython解释器层面的实现细节，我没有逐行看过asyncio的C源码。我的理解是：在实际项目中，我们遇到过一个坑——在async函数里不小心调了同步的requests库（而不是aiohttp），导致整个事件循环被阻塞。排查了好久才发现。所以我的经验是：异步编程关键不在原理多深，而在实践中心里始终清楚'哪些操作会阻塞事件循环'。\n\n"
  "【关键Tips】\n"
  "这道题的核心是展示你'做过真实的技术选型'，不是背书。一定要提到实际踩过的坑（比如同步调用阻塞事件循环），这比背出asyncio原理更有说服力。")

Q("Q2.【L1开场】你这个平台的架构是分层的吗？具体怎么分的？",
  "【你的L1回答】\n"
  "是的，我采用的是经典的四层架构：\n\n"
  "第一层是接入层。用Nginx做反向代理和负载均衡，处理HTTPS终结、静态资源缓存。前端Vue3的SPA应用部署在Nginx后面。\n\n"
  "第二层是API网关层。FastAPI服务作为BFF（Backend For Frontend），接收前端的HTTP请求，做参数校验、认证鉴权、限流。这一层不处理重业务逻辑，主要是路由和编排。\n\n"
  "第三层是业务服务层。这里面包括Prompt管理服务、评测执行服务、报告生成服务、Agent测试服务等。每个服务是独立的Python模块，通过依赖注入的方式组合。\n\n"
  "第四层是基础设施层。包括PostgreSQL（业务数据）、Milvus（向量数据）、Redis（缓存和任务队列的Broker）、Celery Worker（异步执行评测任务）、MinIO（存储评测报告文件）。\n\n"
  "层与层之间通过定义好的接口通信，上层不直接依赖下层的具体实现，方便后续替换组件。\n\n"
  "【L2追问】\n"
  "你说是微服务架构吗？每个服务是独立部署的进程？\n\n"
  "【L2应对】\n"
  "严格来说不是微服务，更准确的说法是'模块化单体'（Modular Monolith）。当前阶段所有业务模块都在同一个FastAPI进程里，只是代码层面做了模块拆分，每个模块有自己独立的router、service、repository层。\n\n"
  "我刻意没有拆成微服务，原因有三：\n"
  "第一，团队规模。目前是我一个人主导开发，微服务带来的运维复杂度（服务发现、配置中心、分布式追踪）ROI太低。\n"
  "第二，业务耦合度。Prompt评测和RAG评测经常需要共享数据集和评测结果，如果拆成两个服务，会产生大量的跨服务调用，反而增加延迟和不稳定性。\n"
  "第三，我在代码层面已经做好了服务边界隔离。每个模块有自己的接口定义（Python Protocol/ABC），如果将来某个模块需要独立扩展，我可以把它抽出来变成独立服务，只需要改依赖注入的配置，业务代码不用动。\n\n"
  "唯一的例外是Celery Worker，评测任务是独立进程跑的，因为评测耗时较长（几分钟到几十分钟），不能阻塞API响应。\n\n"
  "【L3追问】\n"
  "你说用依赖注入实现模块解耦，具体怎么实现的？如果用FastAPI的Depends，它和Java Spring的DI有什么本质区别？\n\n"
  "【L3应对/兜底】\n"
  "我用的是FastAPI原生的Depends机制。比如PromptService依赖PromptRepository和LLMClient，我不在PromptService里new这些对象，而是通过构造函数注入：\n\n"
  "def get_prompt_service(\n"
  "    repo: PromptRepository = Depends(get_prompt_repository),\n"
  "    llm: LLMClient = Depends(get_llm_client)\n"
  ") -> PromptService:\n"
  "    return PromptService(repo, llm)\n\n"
  "FastAPI的Depends会在请求进入时自动解析依赖树，而且是请求级别的（默认scope），每个请求拿到新的实例。\n\n"
  "和Spring的区别：Spring的DI容器是进程级别的单例管理，Bean的生命周期管理很复杂（Singleton、Prototype、Request、Session）。FastAPI的Depends更轻量，本质上就是函数调用链，没有容器概念。\n\n"
  "这个设计带来的好处是：单元测试时我可以轻松Mock任何依赖——直接传一个假对象进去就行，不需要启动Spring容器或做复杂的Mock配置。\n\n"
  "【关键Tips】\n"
  "面试官问'是不是微服务'是在试探你是不是盲目追新技术。'模块化单体'是成熟工程师的答案——你知道微服务好，但更知道什么时候不该用。")

Q("Q3.【L1开场】你这个平台从0到1花了多长时间？你是怎么规划的？",
  "【你的L1回答】\n"
  "从开始调研到第一个可用版本大概花了3个月。我分成了四个阶段：\n\n"
  "第一阶段是调研和方案设计（2周）。调研了市面上已有的AI测试工具（LangSmith、LangFuse、RAGAS、DeepEval），分析各自的优缺点，输出了一份技术选型报告。同时和业务方对齐了核心需求——他们最痛的是Prompt质量不稳定、RAG效果无法量化、Agent行为不可预测。\n\n"
  "第二阶段是MVP开发（4周）。先做了Prompt评测模块，因为这是最痛的。搭好了FastAPI + PostgreSQL的基础架子，实现了Prompt管理、批量执行、指标计算的完整链路。MVP跑通后立刻拿给业务方试用。\n\n"
  "第三阶段是迭代完善（4周）。根据试用反馈加了RAG评测模块、可视化的Grafana看板、以及Agent测试框架。这个阶段大量参考了RAGAS的设计思路。\n\n"
  "第四阶段是稳定和推广（2周）。写了完整的文档和接入指南，帮两个业务团队接入了平台，处理了他们遇到的各种问题。\n\n"
  "【L2追问】\n"
  "你说调研了LangSmith和LangFuse，为什么最后没直接用它们，而是自己做了个平台？\n\n"
  "【L2应对】\n"
  "这是一个很好的问题。LangSmith和LangFuse都是很好的产品，但有几个原因让我们决定自研：\n\n"
  "第一，数据安全。我们的评测数据包含业务敏感的测试用例，放到SaaS平台上（LangSmith是云服务）存在合规风险。虽然LangFuse支持私有化部署，但它对非LangChain生态的支持不够好，我们有些服务用的是原生OpenAI SDK。\n\n"
  "第二，定制化需求。业务方有一些很特殊的评测指标（比如针对车载场景的安全合规检查），市面上的通用平台不支持自定义指标的深度扩展。\n\n"
  "第三，成本。LangSmith按Trace量收费，我们的评测量很大（每次回归跑几百条Prompt），长期来看自研更划算。\n\n"
  "但我也不是闭门造车。LangSmith的Trace设计、LangFuse的Dashboard布局、RAGAS的指标定义，我都借鉴了很多。而且我把平台设计成了插件化架构，如果将来某个模块有更好的开源方案，可以快速替换。\n\n"
  "【L3追问】\n"
  "你说借鉴了LangSmith的Trace设计，那LangSmith的Trace底层是怎么实现的？如果你要实现类似的分布式追踪，你会怎么做？\n\n"
  "【L3应对/兜底】\n"
  "LangSmith的Trace本质上是给LLM调用的每一步（LLM调用、Retriever检索、Tool执行）加上span，形成一个树状的调用链。底层用的是OpenTelemetry协议做数据采集和导出。\n\n"
  "如果我要实现类似的追踪，我会这样做：\n"
  "1. 在每个关键节点（LLM调用前后、检索前后）插入hook/装饰器，自动记录输入输出和时间戳。\n"
  "2. 用contextvars（Python的上下文变量，async safe）传递trace_id和parent_span_id，确保异步环境下父子关系不丢失。\n"
  "3. 数据存到PostgreSQL（元数据）+ ClickHouse（时序数据，如果有大量Trace的话）。\n\n"
  "不过目前我们平台还没有做到分布式追踪的级别，因为评测任务本身就是单进程执行的。如果将来需要跨服务追踪，我会优先考虑集成OpenTelemetry + Jaeger，而不是从零造轮子。\n\n"
  "【关键Tips】\n"
  "核心得分点：展示你知道市面上有什么（不是闭门造车）、知道自研的tradeoff（不是盲目自研）、知道什么时候该用现成的（OpenTelemetry）。这是成熟工程师的思维方式。")

Q("Q4.【L1开场】你说后端用FastAPI，能说说具体的项目结构吗？",
  "【你的L1回答】\n"
  "我的项目结构遵循了FastAPI社区推荐的最佳实践：\n\n"
  "api/ 目录放路由定义，按业务模块拆分：\n"
  "  - api/prompts.py  Prompt管理相关接口\n"
  "  - api/evaluations.py  评测任务接口\n"
  "  - api/reports.py  报告查询接口\n"
  "  - api/agents.py  Agent测试接口\n\n"
  "services/ 目录放业务逻辑：\n"
  "  - services/prompt_service.py  Prompt版本管理、模板渲染\n"
  "  - services/eval_service.py  评测编排、结果汇总\n"
  "  - services/ragas_service.py  RAGAS指标计算封装\n"
  "  - services/llm_client.py  多模型调用的统一封装\n\n"
  "models/ 目录放SQLAlchemy的ORM模型和Pydantic的DTO：\n"
  "  - models/db/  数据库表映射\n"
  "  - models/schemas/  请求/响应的数据结构\n\n"
  "core/ 目录放配置、依赖注入、中间件：\n"
  "  - core/config.py  环境变量和配置\n"
  "  - core/deps.py  FastAPI Depends依赖定义\n"
  "  - core/middleware.py  日志、CORS、异常处理\n\n"
  "tasks/ 目录放Celery异步任务定义。\n\n"
  "tests/ 目录按模块组织单元测试和集成测试。\n\n"
  "这个结构的核心原则是：外层（api）薄，内层（services）厚。路由只做参数校验和结果返回，业务逻辑全在service层，方便测试和复用。\n\n"
  "【L2追问】\n"
  "你说LLM调用的封装在llm_client.py里，具体怎么封装的？怎么支持多个模型？\n\n"
  "【L2应对】\n"
  "我设计了一个统一的LLMClient抽象接口，然后不同模型分别实现：\n\n"
  "class BaseLLMClient(ABC):\n"
  "    @abstractmethod\n"
  "    async def chat(self, messages, **kwargs) -> LLMResponse: ...\n"
  "    @abstractmethod\n"
  "    async def chat_stream(self, messages, **kwargs) -> AsyncIterator: ...\n\n"
  "class OpenAIClient(BaseLLMClient):  封装openai SDK\n"
  "class ClaudeClient(BaseLLMClient):  封装anthropic SDK\n"
  "class LocalModelClient(BaseLLMClient):  调用本地部署的vLLM服务\n\n"
  "LLMResponse是一个统一的数据结构，包含content、token_usage、finish_reason、latency等字段，不管底层是什么模型，上层拿到的响应格式是一样的。\n\n"
  "多模型路由这块我用了一个简单的工厂模式+配置驱动。在配置文件里定义每个场景用哪个模型：\n"
  "{'evaluation': 'gpt-4o', 'chat': 'claude-3-sonnet', 'code_gen': 'deepseek-v3'}\n"
  "然后LLMClientFactory根据配置返回对应的Client实例。这样切换模型只需要改配置，不需要改代码。\n\n"
  "另外我还做了故障转移——如果主模型超时或报错，自动切换到备用模型（比如GPT-4o挂了切到GPT-4o-mini），通过重试机制+熔断器实现。\n\n"
  "【L3追问】\n"
  "你说做了故障转移和熔断器，能具体说说怎么实现的吗？用的什么算法？跟Sentinel/Hystrix有什么关系？\n\n"
  "【L3应对/兜底】\n"
  "熔断器我用的是经典的'三态'模型：关闭(Closed)→打开(Open)→半开(Half-Open)。\n\n"
  "实现上我没有引入Sentinel或Hystrix这样的重框架，而是自己用Redis实现了一个轻量版：\n"
  "- 在Redis里维护一个滑动窗口计数器，统计最近N秒内的失败次数\n"
  "- 当失败次数超过阈值（比如30秒内5次失败），熔断器打开，后续请求直接返回fallback结果，不再调用真实API\n"
  "- 熔断打开后设置一个冷却时间（比如60秒），到期后进入半开状态\n"
  "- 半开状态允许一个探测请求通过，成功就关闭熔断器，失败就重新打开\n\n"
  "为什么用Redis而不是内存？因为Celery Worker是多进程的，内存里的计数器不能跨进程共享。Redis的原子操作（INCR + EXPIRE）天然适合这个场景。\n\n"
  "说实话，我这个实现比较简单，没有做慢调用比例的熔断（只做了失败次数的），也没有区分不同错误类型。如果将来需求更复杂，我会考虑直接集成resilience4j或Python的pybreaker库。\n\n"
  "【关键Tips】\n"
  "这题展示的是'工程化思维'：不是炫耀用了多牛的框架，而是解释清楚'为什么自己实现'和'实现的tradeoff是什么'。承认自己的实现简单但有原因，比吹牛更可信。")

Q("Q5.【L1开场】你们平台怎么处理并发？比如同时有多个评测任务在跑。",
  "【你的L1回答】\n"
  "我们用了Celery来做异步任务处理。用户在Web界面提交评测任务后，FastAPI接口会快速返回一个task_id，实际执行交给Celery Worker在后台跑。\n\n"
  "架构是这样的：\n"
  "- FastAPI作为Producer，把任务消息发到Redis（作为Broker）\n"
  "- 多个Celery Worker进程从Redis取任务执行\n"
  "- 任务执行过程中，Worker实时更新Redis里的任务状态（PENDING→RUNNING→SUCCESS/FAILURE）\n"
  "- 前端通过轮询task_id来获取任务进度和结果\n\n"
  "Worker的数量可以根据CPU核数和任务类型配置。评测任务大多是IO密集型（调LLM API、读写数据库），所以可以配置较多Worker（比如核数×2）。\n\n"
  "另外我用Celery的task routing功能做了任务隔离——快速任务（比如单条Prompt评测）走一个队列，慢任务（比如全量回归）走另一个队列，配不同数量的Worker，避免慢任务把快任务堵住。\n\n"
  "【L2追问】\n"
  "你说用Redis做Broker，Redis是内存数据库，万一Redis挂了或者重启了，任务会不会丢？\n\n"
  "【L2应对】\n"
  "这个问题我们确实遇到过。Redis默认的持久化是RDB快照，如果Redis在两次快照之间挂了，这期间的任务消息确实会丢失。\n\n"
  "我们做了几层防护：\n"
  "第一，开启了Redis的AOF（Append Only File）持久化，每个写操作都记录日志，重启后可以回放恢复。虽然性能有轻微下降，但对于任务系统来说可靠性更重要。\n\n"
  "第二，业务层面做了幂等设计。每个评测任务在数据库里有对应的记录（task表），Celery Worker拿到任务后先检查数据库状态，如果发现这个任务已经执行过了（状态是SUCCESS），就跳过。这样即使消息重复投递，也不会重复执行。\n\n"
  "第三，加了任务超时和重试机制。如果一个任务执行超过30分钟还没有更新状态，Celery的soft_time_limit会触发重试。同时我们在应用层也做了超时检测——另一个定时任务每分钟扫一次数据库，把超过预期执行时间且状态仍是RUNNING的任务标记为TIMEOUT并重试。\n\n"
  "如果业务要求极高可靠性（比如金融场景），我会考虑用RabbitMQ替代Redis做Broker，因为RabbitMQ的消息确认和持久化机制更成熟。但当前阶段Redis够用。\n\n"
  "【L3追问】\n"
  "你提到RabbitMQ的消息确认机制更成熟，能具体说说RabbitMQ的ACK机制和Redis List做队列的本质区别吗？\n\n"
  "【L3应对/兜底】\n"
  "这个问题触及了消息队列设计的核心差异。\n\n"
  "Redis List做队列（我们用的是Celery + Redis broker的组合）：本质上是'取出即删除'。Worker用BRPOP或LPOP从队列取出消息的同时，消息就从Redis里删掉了。如果Worker取到消息后还没来得及处理就挂了，这个消息就永久丢失了。\n\n"
  "RabbitMQ的ACK机制：Worker取到消息后，消息不会立即删除，而是标记为'unacked'状态。只有当Worker处理完成并显式发送ACK后，RabbitMQ才会删除消息。如果Worker挂了没发ACK，RabbitMQ会检测到连接断开，自动把消息重新入队，交给其他Worker处理。\n\n"
  "这是'At-Least-Once'和'At-Most-Once'两种语义的根本差异。Redis默认是At-Most-Once，RabbitMQ通过ACK实现了At-Least-Once。\n\n"
  "Celery其实在应用层做了一些补偿——任务结果存在backend（比如Redis或数据库），但如果broker本身不可靠，补偿也是有限的。这就是为什么高可靠性场景要选RabbitMQ。\n\n"
  "【关键Tips】\n"
  "这道题的核心不是让你讲Celery怎么用，而是展示你理解'消息可靠性'这个分布式系统的基本问题。ACK机制是必考点。")

# 继续 Q6-Q20...
Q("Q6.【L1开场】你们的数据库是怎么设计的？有哪些核心表？",
  "【你的L1回答】\n"
  "核心的表可以分为四类：\n\n"
  "第一类是Prompt相关：\n"
  "- prompt_templates表：存储Prompt模板，字段包括id、name、version、content（模板内容，支持Jinja2变量）、status（draft/published/archived）、created_at、updated_at\n"
  "- prompt_variables表：存储模板的变量定义，关联到template_id\n"
  "- prompt_versions表：每次修改生成一个新版本，做版本历史追踪\n\n"
  "第二类是评测相关：\n"
  "- eval_tasks表：每次评测任务，字段包括task_id、type（prompt_eval/rag_eval/agent_eval）、status、total_count、completed_count\n"
  "- eval_results表：每条测试用例的评测结果，字段包括task_id、test_case_id、metrics（JSON格式存储多维指标）、raw_response、latency_ms\n\n"
  "第三类是测试用例相关：\n"
  "- test_datasets表：测试数据集元信息\n"
  "- test_cases表：具体的测试用例，包括input、expected_output（可选的参考答案）、tags、difficulty\n\n"
  "第四类是Agent测试相关：\n"
  "- agent_tests表：Agent测试定义，包括agent配置、允许的工具列表\n"
  "- tool_simulations表：模拟的工具行为配置（正常返回/异常/超时等）\n"
  "- agent_traces表：Agent执行的全链路追踪，每个step的记录\n\n"
  "所有表都有created_at和updated_at时间戳，方便追溯。关键查询字段都建了索引。\n\n"
  "【L2追问】\n"
  "为什么选PostgreSQL而不是MySQL？MySQL不是更常用吗？\n\n"
  "【L2应对】\n"
  "选PostgreSQL主要有四个原因：\n\n"
  "第一，JSONB支持。我们的eval_results表里metrics字段存的是JSON格式的评测指标，PostgreSQL的JSONB类型可以建GIN索引，支持高效的JSON内字段查询和过滤。比如'查询所有faithfulness低于0.7的评测结果'，用JSONB操作符可以直接在SQL里完成。MySQL的JSON支持较弱，不能建真正的索引。\n\n"
  "第二，CTE（公共表表达式）和窗口函数。评测报告需要做很多复杂的聚合查询，比如'过去30天每天的评测通过率趋势'、'每个Prompt版本的前后对比'。PostgreSQL的CTE让复杂查询更清晰可维护。\n\n"
  "第三，扩展生态。后面我们可能会用到pgvector扩展（直接在PostgreSQL里存embedding做向量检索），这样就不需要额外维护一个Milvus实例，简化架构。PostgreSQL的扩展机制非常成熟。\n\n"
  "第四，License。PostgreSQL是纯BSD协议，没有任何限制。MySQL是Oracle的，虽然社区版也是GPL，但企业使用有一定的合规顾虑。\n\n"
  "当然MySQL也有优势——读性能在某些场景更好、运维人员更熟悉。但对我们这个读多写少、需要复杂查询和JSON处理的分析型场景，PostgreSQL更合适。\n\n"
  "【L3追问】\n"
  "你说JSONB可以建GIN索引，能解释一下GIN索引的原理吗？它和B-Tree索引在JSON查询上有什么本质区别？\n\n"
  "【L3应对/兜底】\n"
  "GIN（Generalized Inverted Index）是倒排索引，核心思想是把复合数据类型（数组、JSON、全文搜索的文本）分解成多个key，每个key指向包含它的行。\n\n"
  "B-Tree索引适合等值查询和范围查询，但它索引的是整个字段的值。对于JSONB里的某个key，B-Tree需要建表达式索引（比如CREATE INDEX ON table ((data->>'field'))），只能针对特定字段。\n\n"
  "GIN索引的威力在于：一个GIN索引可以支持JSONB中任意key的查询。比如data @> '{\"faithfulness\": 0.5}'（包含查询）、data ? 'field'（key存在性查询），都能用同一个GIN索引加速。\n\n"
  "代价是写入性能——每次INSERT/UPDATE都需要更新倒排索引，比B-Tree慢。但我们的场景是评测结果写一次、读多次，所以读优化的GIN更合适。\n\n"
  "【关键Tips】\n"
  "PostgreSQL vs MySQL 是经典面试题。关键不是说出谁好谁坏，而是能结合自己的业务场景说出选型理由。提到JSONB + GIN索引能展示你的数据库功底。")

Q("Q7.【L1开场】你们前端是怎么做的？用的什么框架？",
  "【你的L1回答】\n"
  "前端用的是Vue3 + Vite + Element Plus + Pinia。\n\n"
  "选择Vue3的原因：第一，Vue3的Composition API让组件逻辑更容易复用，特别是我们有很多相似的评测结果展示组件。第二，TypeScript支持比Vue2好很多。第三，Vite的HMR（热模块替换）开发体验很好。\n\n"
  "状态管理用Pinia替代了Vuex，因为Pinia对TypeScript的支持更友好，API更简洁。\n\n"
  "页面结构分几个模块：\n"
  "- Dashboard首页：展示评测任务概览、最近的评测趋势图（用ECharts）\n"
  "- Prompt管理页：列表、编辑器、版本历史对比\n"
  "- 评测中心：创建评测任务、实时查看进度\n"
  "- 报告页：评测结果的详细展示、多维指标对比\n"
  "- Agent测试页：配置测试场景、查看Agent执行Trace\n\n"
  "前后端通信统一用Axios，封装了请求拦截器（自动加Token、统一错误处理）和响应拦截器（统一toast提示）。\n\n"
  "【L2追问】\n"
  "为什么选Vue3而不是React？现在React好像更主流吧？\n\n"
  "【L2应对】\n"
  "这个选型我确实纠结过。React生态更大、岗位更多是不争的事实，但对我们这个项目来说，Vue3有几个优势：\n\n"
  "第一，上手成本。这个平台后续可能需要其他测试同事参与维护，Vue3的模板语法（SFC单文件组件）对非专业前端的同事更友好，学习曲线比JSX平缓。\n\n"
  "第二，响应式系统。Vue3的Proxy-based响应式是自动的，不需要像React那样手动管理依赖数组（useMemo/useCallback）。对于数据展示密集的评测平台，少写很多样板代码。\n\n"
  "第三，生态统一。Element Plus（Vue3的UI库）质量很高，组件齐全，对中后台场景的支持比Ant Design（React）的表格、表单更友好。\n\n"
  "当然，如果我加入的是一个React技术栈的团队，我完全可以用React。我理解React的核心概念（Hooks、虚拟DOM、Fiber架构），迁移成本不高。关键是根据项目特点做选择，而不是'我只会Vue'。\n\n"
  "【L3追问】\n"
  "你说理解React的Fiber架构，能简单说说Fiber解决了什么问题吗？和Vue3的响应式更新机制有什么本质区别？\n\n"
  "【L3应对/兜底】\n"
  "React Fiber核心解决的是'可中断的渲染'。在Fiber之前，React的reconciler是递归的，一旦开始渲染整棵树就不能停，如果组件树很大，会长时间占用主线程，导致页面卡顿。\n\n"
  "Fiber把渲染工作拆成一个个小单元（Fiber节点），每个单元执行完后检查有没有更高优先级的任务（比如用户输入），有就让出主线程，没就继续。这叫做'时间切片'（Time Slicing）。\n\n"
  "Vue3的更新机制不同。Vue3的响应式系统在数据变化时就能精确定位到哪些组件需要更新（通过Proxy的依赖追踪），不需要像React那样从根节点开始遍历整棵树。所以Vue3的更新粒度更细，效率更高，不需要Fiber那样的可中断调度。\n\n"
  "简单说：React的策略是'我全部重新算，但可以中断'；Vue3的策略是'我只算需要更新的部分，一口气算完'。\n\n"
  "【关键Tips】\n"
  "Vue vs React是前端高频题。你的优势是'全栈'，所以别只说Vue好，要展示你理解两者差异，展现技术广度。")

Q("Q8.【L1开场】你们平台的认证和权限是怎么做的？",
  "【你的L1回答】\n"
  "当前阶段我们用的是JWT（JSON Web Token）方案。用户登录后，后端签发一个JWT Token，包含用户ID和角色信息。前端把Token存在localStorage，每次请求在Header里带Authorization: Bearer <token>。后端通过FastAPI的Depends做Token校验。\n\n"
  "权限控制用的是RBAC（基于角色的访问控制），定义了三种角色：\n"
  "- Admin：可以管理用户、查看所有数据\n"
  "- Editor：可以创建/编辑Prompt和测试用例，发起评测\n"
  "- Viewer：只能查看评测结果和报告\n\n"
  "在FastAPI的路由层面，我用装饰器/Depends做权限校验：\n"
  "@router.post('/prompts')\n"
  "async def create_prompt(data, current_user = Depends(require_role('editor'))):\n\n"
  "这样每个接口都能精确控制访问权限。\n\n"
  "【L2追问】\n"
  "JWT Token过期了怎么办？你怎么处理Token刷新？\n\n"
  "【L2应对】\n"
  "我采用的是双Token机制：Access Token（短期，30分钟过期）+ Refresh Token（长期，7天过期）。\n\n"
  "流程是这样的：\n"
  "1. 登录时返回access_token和refresh_token\n"
  "2. 前端每次请求带access_token\n"
  "3. 后端检测到access_token过期时返回401\n"
  "4. 前端的Axios响应拦截器捕获401，自动用refresh_token去调用/refresh接口获取新的access_token\n"
  "5. 拿到新token后重试原来的请求，用户无感知\n"
  "6. 如果refresh_token也过期了，就跳转到登录页\n\n"
  "Refresh Token存在数据库里，可以随时吊销（比如用户改密码后把该用户所有refresh_token标记为失效）。这样即使access_token被盗，也只有30分钟的风险窗口。\n\n"
  "【L3追问】\n"
  "你说Refresh Token存在数据库里，那每个请求都要查数据库验证Token吗？会不会成为性能瓶颈？\n\n"
  "【L3应对/兜底】\n"
  "好问题。Refresh Token只在调用/refresh接口时才需要查数据库验证，普通API请求只验证Access Token，而Access Token的验证是无状态的——后端只需要用密钥验证签名和过期时间，不需要查数据库。\n\n"
  "所以性能瓶颈不存在。Refresh接口的调用频率远低于普通API（30分钟才一次），数据库压力可以忽略。\n\n"
  "至于Access Token吊销的问题（比如管理员想立即踢掉某个用户），确实是无状态JWT的固有问题。解决方案有几个：\n"
  "1. 维护一个黑名单（Redis存被吊销的Token ID），每次验证时查一下\n"
  "2. 缩短Access Token的有效期到5-10分钟，减少风险窗口\n"
  "3. 改用有状态的Session方案（但会牺牲水平扩展能力）\n\n"
  "目前我们平台对实时吊销的要求不高，所以选了方案2（较短的Token有效期），够用。\n\n"
  "【关键Tips】\n"
  "JWT + Refresh Token是最常见方案，但关键是要能说出'无状态验证 vs 实时吊销'这个tradeoff。这是区分'会用'和'理解'的分界线。")

Q("Q9.【L1开场】你提到用了Docker Compose部署，具体怎么部署的？",
  "【你的L1回答】\n"
  "整个平台用Docker Compose管理，一个docker-compose.yml文件定义所有服务：\n\n"
  "- nginx：前端静态资源 + 反向代理\n"
  "- backend：FastAPI应用\n"
  "- celery_worker：异步任务Worker（可以scale多个）\n"
  "- celery_beat：定时任务调度\n"
  "- postgres：业务数据库\n"
  "- redis：缓存 + Celery Broker\n"
  "- milvus：向量数据库（用于评测embedding）\n\n"
  "每个服务有独立的Dockerfile或直接使用官方镜像。服务间通过Docker网络通信，用服务名作为hostname（比如backend连postgres，host直接用'postgres'）。\n\n"
  "配置通过环境变量注入，有.env文件区分开发/生产环境。敏感信息（数据库密码、API Key）不写死在代码里。\n\n"
  "部署命令就一条：docker compose up -d，然后nginx映射80端口对外提供服务。\n\n"
  "【L2追问】\n"
  "Docker Compose适合生产环境吗？如果服务挂了怎么自动恢复？\n\n"
  "【L2应对】\n"
  "Docker Compose在单机小规模部署下是可以用于生产的，但需要做一些额外配置：\n\n"
  "第一，容器的restart策略。我在docker-compose.yml里对所有服务设置了restart: unless-stopped，这样Docker守护进程重启或容器异常退出时会自动重启。\n\n"
  "第二，健康检查。关键服务（backend、postgres、redis）配了healthcheck，比如backend的healthcheck是curl /health接口，postgres用pg_isready命令。依赖关系用depends_on + condition: service_healthy确保启动顺序。\n\n"
  "第三，日志管理。配了日志驱动和日志轮转（json-file + max-size + max-file），避免磁盘被日志撑爆。\n\n"
  "但Docker Compose的局限也很明显：不能跨机器部署、没有服务发现、没有负载均衡。如果将来需要多机部署或高可用，我会迁移到Kubernetes或Docker Swarm。目前单机能满足需求，不需要引入K8s的复杂度。\n\n"
  "【L3追问】\n"
  "如果迁移到Kubernetes，你的服务需要做哪些改造？\n\n"
  "【L3应对/兜底】\n"
  "迁移到K8s主要需要做以下改造：\n\n"
  "1. 配置管理：环境变量从.env迁移到ConfigMap和Secret，敏感信息用K8s Secret加密存储。\n\n"
  "2. 服务发现：FastAPI连接PostgreSQL的host从Docker服务名改为K8s Service的DNS名（如postgres-service.default.svc.cluster.local）。\n\n"
  "3. 持久化存储：PostgreSQL和Milvus的数据需要挂载PersistentVolume（PVC），不能依赖容器本地存储。\n\n"
  "4. 健康检查：Docker Compose的healthcheck迁移为K8s的livenessProbe和readinessProbe。\n\n"
  "5. 水平扩展：Celery Worker可以用Deployment管理，配HPA（水平自动伸缩）根据队列长度自动增减Pod数量。\n\n"
  "6. Ingress：Nginx反向代理改为K8s Ingress Controller（如nginx-ingress），管理外部流量入口。\n\n"
  "7. 日志和监控：集成Prometheus + Grafana做集群监控，EFK/ELK做日志收集。\n\n"
  "核心原则是：应用代码尽量不改，只改部署配置。这也是我们一开始就用环境变量做配置管理的原因——迁移时只需要改注入方式。\n\n"
  "【关键Tips】\n"
  "Docker Compose vs K8s 是架构题。展示你知道各自的适用边界——小规模用Compose（简单），大规模用K8s（复杂但有价值），不要盲目追K8s。")

Q("Q10.【L1开场】你们平台的日志和监控怎么做的？",
  "【你的L1回答】\n"
  "日志层面：用Python标准库的logging模块，配了结构化日志（JSON格式），包含request_id、user_id、模块名、时间戳等字段。日志输出到stdout，由Docker的日志驱动收集。这样在开发环境可以直接看控制台，生产环境可以用docker logs查看。\n\n"
  "监控层面分三块：\n"
  "1. 基础设施监控：用Prometheus + Node Exporter监控CPU、内存、磁盘等主机指标，Grafana做可视化。\n"
  "2. 应用监控：FastAPI集成了prometheus_fastapi_instrumentator包，自动暴露请求数、响应时间、错误率等指标给Prometheus。\n"
  "3. 业务监控：评测任务的执行情况（成功/失败/超时数量、平均执行时间），通过自定义指标推送到Prometheus Pushgateway（因为Celery Worker是短生命周期任务）。\n\n"
  "告警用Grafana Alerting，配了关键指标告警（比如评测任务连续失败3次就发企业微信通知）。\n\n"
  "【L2追问】\n"
  "你说用Prometheus Pushgateway处理Celery Worker的指标，为什么不直接用Prometheus的拉模式？Pushgateway有什么坑？\n\n"
  "【L2应对】\n"
  "Prometheus的设计哲学是'拉'模式（Pull），定期去目标服务抓取/metrics接口。但Celery Worker是短生命周期任务——执行完就结束，Prometheus来不及拉取。所以用Pushgateway作为中间缓冲——Worker执行完把指标推送到Pushgateway，Prometheus再从Pushgateway拉取。\n\n"
  "Pushgateway的坑我踩过：\n"
  "第一，Pushgateway不会自动清理过期指标。如果Worker推送后异常退出没有清理，指标会一直留在Pushgateway里，导致Prometheus拿到脏数据。解决方案是设置合理的指标过期时间，或者在任务开始时就推送一个初始值，结束后推送最终值。\n\n"
  "第二，Pushgateway是单点。如果它挂了，所有Worker的指标都丢了。目前我们单机部署，这个风险可控。如果是生产级集群，可以考虑用VictoriaMetrics或Grafana Agent替代。\n\n"
  "【L3追问】\n"
  "你能解释一下Prometheus的TSDB（时序数据库）的底层存储原理吗？为什么它压缩率那么高？\n\n"
  "【L3应对/兜底】\n"
  "Prometheus的TSDB核心设计有两个关键：\n\n"
  "第一是样本压缩。它不存原始时间戳，而是利用'时间序列数据是等间隔采样'这个特性，只存起始时间戳+采样间隔+一系列值。这样时间戳的存储开销几乎为零。\n\n"
  "第二是Gorilla论文的压缩算法。对时序数据值做XOR编码——相邻时间点的浮点数值通常变化很小，XOR后会产生大量前导零和尾随零，再用变长编码压缩。\n\n"
  "更深层的实现细节（比如chunk的组织方式、倒排索引结构），我没有深入研究过TSDB的源码。但我的理解是：选型时知道它能达到原始数据的10-30%压缩比就够了，关键在于怎么用好它。\n\n"
  "【关键Tips】\n"
  "Pushgateway的坑是实操经验，比背出Prometheus原理更有价值。最后对TSDB原理的回答展示了你'知道边界'的诚实态度。")

# 继续生成 Q11-Q20（架构相关的剩余题目）
Q("Q11.【L1开场】你这个平台的API接口是怎么设计的？遵循什么规范吗？",
  "【你的L1回答】\n"
  "我遵循的是RESTful API设计规范，核心原则：\n\n"
  "1. URL用名词复数表示资源：GET /api/v1/prompts（列表）、POST /api/v1/prompts（创建）、GET /api/v1/prompts/{id}（详情）\n"
  "2. HTTP动词表达操作：GET查询、POST创建、PUT全量更新、PATCH部分更新、DELETE删除\n"
  "3. 版本化：URL前缀带版本号/api/v1/，方便后续API升级时兼容旧版本\n"
  "4. 统一响应格式：{code: 0, message: 'success', data: {...}}，错误时{code: 错误码, message: '错误描述'}\n"
  "5. 分页：列表接口统一支持page和page_size参数，响应包含total、page、page_size、items\n"
  "6. 过滤和排序：用查询参数实现，如GET /api/v1/eval_results?task_id=xxx&sort=-created_at\n\n"
  "FastAPI的Pydantic模型自动生成了OpenAPI（Swagger）文档，我还在模型里加了Field的description和example，让文档更可读。\n\n"
  "【L2追问】\n"
  "你提到API版本化，如果v2版本有一个接口的响应格式变了，你怎么保证不影响v1的客户端？\n\n"
  "【L2应对】\n"
  "我在代码层面做了版本隔离。每个API版本有独立的路由文件：\n"
  "- api/v1/prompts.py\n"
  "- api/v2/prompts.py\n\n"
  "在FastAPI的主应用里挂载：\n"
  "app.include_router(v1_router, prefix='/api/v1')\n"
  "app.include_router(v2_router, prefix='/api/v2')\n\n"
  "两个版本可以有不同的Pydantic Schema和业务逻辑，互不影响。v1的接口会一直保留直到所有客户端迁移完毕。\n\n"
  "另外，版本号放在URL里而不是Header里是有意为之——URL版本化对调用方更直观，调试时看URL就知道用哪个版本。Header版本化虽然'更RESTful'，但实际使用中容易出错。\n\n"
  "【L3追问】\n"
  "你说Header版本化'更RESTful'但容易出错，能具体说说为什么吗？业界主流做法是什么？\n\n"
  "【L3应对/兜底】\n"
  "Header版本化的问题在于：API版本变成一个隐式约定。调用方需要在每次请求时记得带Accept: application/vnd.api.v2+json这样的Header，一旦漏了就回到默认版本，排查问题很困难。\n\n"
  "URL版本化的好处是：版本信息在URL里一目了然，代理服务器（Nginx）可以基于URL做路由，API网关可以基于URL做版本级的限流和统计。\n\n"
  "业界主流：Google、GitHub、Stripe都用URL版本化。Stripe更有意思——他们的API用日期做版本（如/v1/2023-08-01/），这样版本号和发布时间直接关联，非常直观。\n\n"
  "【关键Tips】\n"
  "API设计是后端基本功。能说出URL版本化 vs Header版本化的tradeoff，并引用大厂实践，显得你有行业视野。")

Q("Q12.【L1开场】你说前端有实时展示评测进度的功能，这个怎么实现的？",
  "【你的L1回答】\n"
  "评测进度的实时更新用了几种方式：\n\n"
  "1. 简单方案：前端定时轮询。每2-3秒发一次GET请求查询任务状态，后端返回当前的completed_count和total_count，前端算百分比展示进度条。实现简单，适合大多数场景。\n\n"
  "2. 对于需要更实时反馈的场景（比如Agent测试的逐Step展示），用了Server-Sent Events（SSE）。FastAPI支持StreamingResponse，后端用async generator逐条推送Agent的每个执行步骤，前端用EventSource接收并实时渲染。\n\n"
  "选SSE而不是WebSocket的原因：评测进度是单向数据流（服务端→客户端），不需要双向通信。SSE基于HTTP，穿透代理和防火墙更容易，浏览器原生支持EventSource API。WebSocket对单向推送来说是杀鸡用牛刀。\n\n"
  "【L2追问】\n"
  "SSE在连接断开后怎么处理？能自动重连吗？\n\n"
  "【L2应对】\n"
  "SSE的自动重连是EventSource API原生支持的。浏览器在连接断开后会自动尝试重连，间隔时间可以通过服务端发送的retry字段控制。\n\n"
  "但自动重连有个问题：重连后是从头开始推送还是从断点续传？\n\n"
  "我的处理方式是：服务端在推送每条消息时带一个sequence_id（递增序号），前端维护last_received_seq。重连时前端在URL参数里带上?last_event_id=xxx，后端根据这个ID找到断点，从下一条开始推送。\n\n"
  "如果服务端没有保存事件历史（比如Celery Worker已经执行完了），那就返回当前最新状态，前端直接跳到最新状态展示，不重放历史。\n\n"
  "【L3追问】\n"
  "你说FastAPI用StreamingResponse实现SSE，但如果部署在Nginx后面，Nginx默认会缓冲响应，你怎么处理的？\n\n"
  "【L3应对/兜底】\n"
  "这确实是个实际踩过的坑。Nginx默认会开启代理缓冲（proxy_buffering on），会把后端的响应先缓存起来，等凑够一定大小再发给客户端，这样SSE就变成'等半天突然弹一堆'。\n\n"
  "解决方案：在Nginx配置里对SSE接口的location关掉缓冲：\n"
  "proxy_buffering off;\n"
  "proxy_cache off;\n"
  "proxy_set_header X-Accel-Buffering no;\n\n"
  "另外在FastAPI的响应里也要加Header：\n"
  "Cache-Control: no-cache\n"
  "Connection: keep-alive\n"
  "X-Accel-Buffering: no\n\n"
  "这样确保从应用到反向代理整个链路都不缓冲，消息能实时推送到前端。\n\n"
  "【关键Tips】\n"
  "SSE + Nginx缓冲冲突是非常实战的坑，能说出来证明你真正部署过、踩过坑，而不是只在本地跑过demo。")

Q("Q13.【L1开场】你提到前端用ECharts做可视化，具体展示了哪些图表？",
  "【你的L1回答】\n"
  "Dashboard上主要展示了这些图表：\n\n"
  "1. 评测任务概览卡片：今日执行任务数、成功率、平均耗时等关键数字，用Stat卡片展示。\n\n"
  "2. 评测趋势折线图：过去30天每天评测通过率的变化趋势，X轴是日期，Y轴是通过率百分比。如果某天突然下降，能快速发现。\n\n"
  "3. Prompt版本对比柱状图：选两个Prompt版本，把faithfulness、relevancy、precision、recall等指标并排展示，直观看到哪个版本更好。\n\n"
  "4. 指标分布热力图：展示不同测试数据集在不同指标上的得分分布，帮助发现哪些场景是短板。\n\n"
  "5. Agent Trace时序图：展示Agent多步推理的时间线，每一步的耗时、使用的工具、输入输出，类似Jaeger的Gantt图。\n\n"
  "图表数据通过独立的统计API获取（后端预聚合好，前端只负责渲染），不直接在前端做大量计算。\n\n"
  "【L2追问】\n"
  "如果评测数据量很大（比如上百万条），统计API怎么保证性能？后端怎么做聚合？\n\n"
  "【L2应对】\n"
  "这个问题分几个层次解决：\n\n"
  "第一层，数据库层面：在eval_results表上建了合理的索引（task_id + created_at的复合索引），常用的聚合查询能走索引覆盖。\n\n"
  "第二层，预聚合：对于Dashboard的汇总数据（每日趋势），不用每次请求都实时聚合。我用Celery Beat定时任务（每小时跑一次），把聚合结果写入一张单独的dashboard_stats表。前端请求Dashboard时直接查这张小表，毫秒级响应。\n\n"
  "第三层，缓存：对于变化不频繁的数据（比如30天趋势），在Redis里缓存结果，设置合理的TTL（比如5分钟），减少数据库压力。\n\n"
  "如果数据量到百万级别，我会考虑引入列式数据库（如ClickHouse）专门做分析查询，PostgreSQL继续负责事务型操作。这是OLTP和OLAP分离的思路。\n\n"
  "【L3追问】\n"
  "你说OLTP和OLAP分离，那数据怎么从PostgreSQL同步到ClickHouse？实时性要求多高？\n\n"
  "【L3应对/兜底】\n"
  "数据同步方案有几种：\n\n"
  "1. CDC（Change Data Capture）：用Debezium监听PostgreSQL的WAL日志，把变更实时推送到Kafka，再写入ClickHouse。优点是实时性高（秒级延迟），缺点是需要额外维护Kafka和Debezium。\n\n"
  "2. 定时批量同步：用DataX或自定义脚本，每小时/每天把增量数据导入ClickHouse。简单但延迟高。\n\n"
  "对于评测场景，我不需要实时（T+0），T+1小时甚至T+1天都能接受——毕竟你看趋势图也不差那一小时。所以定时批量同步完全够用。\n\n"
  "但如果面试官问的是实时场景（比如在线服务的监控告警），那就要走CDC方案。关键是根据业务需求选择合适的方案，不是越实时越好。\n\n"
  "【关键Tips】\n"
  "OLTP/OLAP分离是架构基本功。能说出'根据业务需求选方案，不是越实时越好'体现了务实思维。CDC/DataX这些具体方案名字说出来增加可信度。")

Q("Q14.【L1开场】你提到测试数据集的管理，你们怎么管理测试用例的？有版本控制吗？",
  "【你的L1回答】\n"
  "测试数据集我们用Git做版本管理，遵循'Test as Code'的理念。\n\n"
  "具体做法：\n"
  "1. 测试用例以JSON/YAML格式存在Git仓库的test_data/目录下，按场景分文件（如prompt_eval_cases.json、rag_eval_cases.json）。\n"
  "2. 每次修改测试用例走Pull Request流程，需要Review。CI会自动跑一个校验脚本——检查JSON格式是否正确、必填字段是否完整、有没有重复用例。\n"
  "3. 平台有一个'同步'按钮，点击后从Git拉取最新的测试数据到数据库。数据库里保留历史版本记录，可以对比不同版本的数据变化。\n"
  "4. 评测任务创建时可以选择用哪个版本的测试数据集，方便A/B对比——同一个Prompt用不同版本的数据集跑，看兼容性。\n\n"
  "这样做的核心好处：测试数据像代码一样可追溯、可Review、可回滚。\n\n"
  "【L2追问】\n"
  "Git管理测试数据有什么局限性？比如非技术人员怎么操作？\n\n"
  "【L2应对】\n"
  "Git的门槛确实是最大的问题。业务方的测试同学不一定熟悉Git操作。\n\n"
  "我们的解决方案是：在平台上提供了Web界面的测试用例编辑器（表格形式），非技术人员可以直接在浏览器里增删改测试用例。Web编辑器的背后会自动生成Git commit并推送到仓库，操作者不需要知道Git的存在。\n\n"
  "技术上，我们用Python的GitPython库在后端操作Git：\n"
  "- 用户保存用例 → 后端在临时目录clone仓库 → 修改JSON文件 → git add + git commit + git push\n"
  "- commit message自动带上用户ID和操作时间，方便追溯\n\n"
  "这样兼顾了Git的版本控制能力和Web的易用性。Git是专业人士的底层工具，Web是所有人的交互界面，各司其职。\n\n"
  "【L3追问】\n"
  "如果两个人同时在Web界面上修改同一个测试用例文件，Git会产生冲突。你怎么处理？\n\n"
  "【L3应对/兜底】\n"
  "这个问题我们确实遇到过。处理策略分几个层面：\n\n"
  "1. 预防层面：在Web编辑器里加乐观锁——用户打开编辑页面时记录当前数据的版本号（Git commit hash），保存时检查版本号是否变化。如果变了，提示'数据已被他人修改，请刷新后重新编辑'。\n\n"
  "2. 如果真的产生Git冲突（比如有人直接push到仓库绕过了Web），后端push失败时会捕获GitCommandError，自动回滚本地修改，通知用户操作失败并提示联系管理员。\n\n"
  "3. 最坏情况：手动解决。管理员登录服务器，手动git pull --rebase处理冲突。这种情况极少发生，因为我们的并发编辑场景很少。\n\n"
  "说实话，我们没有做'自动合并'——JSON文件的自动合并风险太大，可能产生合法但不正确的JSON。人工介入是最安全的方式。\n\n"
  "【关键Tips】\n"
  "Git + Web编辑器的组合方案非常实用。乐观锁处理并发编辑冲突是进阶回答，体现你对'协作编辑'这个复杂问题的思考。")

Q("Q15.【L1开场】你的平台有没有做自动化CI/CD集成？怎么做的？",
  "【你的L1回答】\n"
  "有，我们集成了GitLab CI。核心流水线分两个场景：\n\n"
  "场景一：Prompt变更自动评测\n"
  "- 开发者修改Prompt模板文件并提交MR\n"
  "- CI检测到prompts/目录下的文件变更，自动触发评测流水线\n"
  "- 流水线步骤：拉取最新测试数据集 → 调用平台API发起评测任务 → 轮询任务状态直到完成 → 获取评测结果\n"
  "- 如果核心指标（faithfulness、relevancy）低于设定的阈值，CI标记为Failed，阻止MR合并\n"
  "- CI会生成一个评测报告摘要，自动评论到MR里\n\n"
  "场景二：平台自身的代码质量\n"
  "- 后端：pytest跑单元测试 + flake8/pylint代码规范检查 + bandit安全检查\n"
  "- 前端：vitest跑组件测试 + ESLint代码规范\n"
  "- Docker镜像构建并推送到私有Registry\n\n"
  "CI/CD的核心价值：Prompt变更不再是'我感觉好像好一点'，而是有数据支撑的'通过率从85%提升到92%'。这让非技术决策者也能量化理解AI质量的改善。\n\n"
  "【L2追问】\n"
  "你提到CI轮询平台API等待评测完成，如果评测要跑30分钟，CI Runner会一直占着吗？这成本很高吧？\n\n"
  "【L2应对】\n"
  "确实，如果CI同步等待，一个Runner就被占住半小时，资源浪费严重。\n\n"
  "我们的解决方案是异步触发+Webhook回调：\n"
  "1. CI只负责触发评测任务（POST /api/v1/eval_tasks，拿到task_id）\n"
  "2. 然后在平台上配置了Webhook——评测任务完成后，平台主动回调GitLab的Pipeline API，通知结果\n"
  "3. CI流水线在触发任务后就结束了（状态是passed with warning），真正的'门禁'逻辑在Webhook回调里：如果指标不达标，平台调用GitLab API把MR标记为'不能合并'并添加评论\n\n"
  "这样CI Runner不需要等待，评测时间从30分钟变成3秒（只发一次HTTP请求）。\n\n"
  "【L3追问】\n"
  "Webhook回调失败了怎么办？比如平台回调GitLab时网络不通？\n\n"
  "【L3应对/兜底】\n"
  "Webhook的可靠性我们做了三层保障：\n\n"
  "1. 重试机制：回调失败后，按指数退避策略重试（1s → 2s → 4s → 8s → 16s），最多重试5次。用Celery的retry + countdown实现。\n\n"
  "2. 兜底定时任务：每10分钟跑一个定时任务，扫描最近完成的评测任务中'还没回调成功'的，补发回调。这样即使所有重试都失败，10分钟内也能补救。\n\n"
  "3. 告警：如果某个任务的回调一直失败（超过30分钟），触发企业微信告警，人工介入。\n\n"
  "Webhook的可靠性是分布式系统的经典问题。没有100%可靠，但可以通过'重试 + 兜底 + 告警'把失败概率降到可接受范围。\n\n"
  "【关键Tips】\n"
  "CI/CD异步化是实际生产环境的常见需求。Webhook的可靠性保障（重试+兜底+告警）是成熟的工程实践。")

# 由于输出限制，Q16-Q120将在后续文件中继续
# 此处为示意结构，实际会生成全部120题
