# Generated by Django 4.2.7 on 2026-07-09 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, max_length=50, verbose_name='任务类型')),
                ('user_request', models.TextField(verbose_name='用户请求')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('steps_count', models.PositiveIntegerField(default=0, verbose_name='执行步骤数')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Agent 任务',
                'verbose_name_plural': 'Agent 任务',
                'db_table': 'agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, help_text='对应 Agent 类的 name 属性，如 "test_case_generator"', max_length=100, verbose_name='Agent 名称')),
                ('prompt_subtype', models.CharField(default='default', help_text='同一 Agent 不同策略的 prompt，如 standard/smart/boundary', max_length=50, verbose_name='Prompt 子类型')),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('user', 'User Prompt 模板')], default='system', max_length=20, verbose_name='Prompt 类型')),
                ('system_prompt', models.TextField(blank=True, help_text='核心提示词内容', verbose_name='System Prompt')),
                ('user_prompt_template', models.TextField(blank=True, help_text='用户消息模板（支持 {变量} 占位）', verbose_name='User Prompt 模板')),
                ('description', models.CharField(blank=True, help_text='此 Prompt 的用途说明', max_length=200, verbose_name='描述')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent Prompt 配置',
                'verbose_name_plural': 'Agent Prompt 配置',
                'db_table': 'agent_prompt_configs',
                'ordering': ['agent_name', 'prompt_subtype'],
                'unique_together': {('agent_name', 'prompt_subtype')},
            },
        ),
    ]
