"""
Django settings for ai_test_platform project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# ============================================================
# Monkey-patch: 修复 langchain_core 版本兼容性问题
# langchain_openai 依赖 ContextOverflowError, 但高版本已移除
# 开发环境不需要 context overflow 严格校验, 补一个假类
# ============================================================
try:
    from langchain_core import exceptions as lc_exc
except ImportError:
    pass
else:
    if not hasattr(lc_exc, 'ContextOverflowError'):
        class _ContextOverflowError(lc_exc.LangChainException):
            """开发环境兼容补丁 - 实际不触发"""
            pass
        lc_exc.ContextOverflowError = _ContextOverflowError

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 明确加载项目根目录 .env，避免从 backend 子目录启动时找不到
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须通过环境变量注入，不提供默认值
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    import secrets
    if os.getenv('DEBUG', '').lower() in ('true', '1', 'yes'):
        # 开发模式：自动生成临时密钥（重启后失效）
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise RuntimeError(
            "SECRET_KEY 环境变量未设置！"
            "生产环境必须设置 SECRET_KEY，开发环境可设置 DEBUG=True 以自动生成临时密钥。"
        )

# 服务间通行令牌：编排服务 ↔ Django MCP 内部调用
# 生产环境必须通过环境变量注入
SERVICE_TOKEN = os.getenv('SERVICE_TOKEN')
if not SERVICE_TOKEN:
    import secrets as _secrets
    if os.getenv('DEBUG', '').lower() in ('true', '1', 'yes'):
        SERVICE_TOKEN = _secrets.token_urlsafe(32)
    else:
        raise RuntimeError(
            "SERVICE_TOKEN 环境变量未设置！"
            "生产环境必须设置 SERVICE_TOKEN，开发环境可设置 DEBUG=True 以自动生成。"
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',  # 必须在 staticfiles 之前 (ASGI)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    # Local apps
    'accounts',
    'testcases',
    'execution',
    'reports',
    'testsuites',
    'knowledge_base',
    'data_factory',  # 数据工厂模块
    'quality_checker',  # 质量数字人模块
    'django_celery_results',  # Celery 结果持久化
    'ai_evaluator',  # AI测评师模块
    'agent_gateway',  # Agent 网关 — 统一 AI 入口
    'web_testcases',  # Web 自动化测试（双引擎：Playwright + AI）
    'performance',    # 性能测试（Locust 压测引擎）
    'demo_api',       # Demo API 示例模块（供测试平台验证用）
]

MIDDLEWARE = [
    'core.middleware.RequestIDMiddleware',
    'core.otel_middleware.OTelTracingMiddleware',  # 全链路追踪：最顶端，最先注入 trace_id
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_test_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_test_platform.wsgi.application'

# ============================================================
# ASGI 配置（用于 SSE 流式场景，支持异步非阻塞 I/O）
# ============================================================
ASGI_APPLICATION = 'ai_test_platform.asgi.application'

# 禁用流式响应的缓冲，确保 SSE 实时推送
# Django 开发服务器 (runserver) 默认每 65536 字节刷新一次
# 我们通过 Gunicorn 运行时使用 --worker-class gevent 或 --worker-class uvicorn
# 开发环境下可通过此设置减小缓冲
_STREAMING_BUFFER_SIZE = 1  # 最小缓冲，逐字符发送


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 数据库配置：支持 SQLite（开发）和 PostgreSQL（生产/Docker）
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'ai_test_platform'),
            'USER': os.getenv('DB_USER', 'ai_test_user'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
    if not DATABASES['default']['PASSWORD']:
        raise RuntimeError(
            "DB_PASSWORD 环境变量未设置！PostgreSQL 需要数据库密码。"
        )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/assets/'
STATICFILES_DIRS = [BASE_DIR / 'assets']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'core.auth.service_auth.ServiceTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Configuration
# 开发环境全开放，生产环境通过环境变量控制
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'True').lower() in ('true', '1', 'yes')
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
CORS_ALLOW_CREDENTIALS = True

# ============================================================
# 多模型 API Key 配置
# ============================================================
# 通义千问 (DashScope) - 默认
DASHSCOPE_API_KEY = os.getenv('DASHSCOPE_API_KEY', '')
# 百炼平台专属地址（如果用百炼而非 DashScope，设置此地址）
# 格式: https://xxx.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
DASHSCOPE_BASE_URL = os.getenv('DASHSCOPE_BASE_URL', '')
# DeepSeek - https://platform.deepseek.com/
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
# 智谱 GLM - https://open.bigmodel.cn/
GLM_API_KEY = os.getenv('GLM_API_KEY', '')
# 硅基流动 (SiliconFlow) - 统一入口，免费用多种模型 - https://siliconflow.cn/
SILICONFLOW_API_KEY = os.getenv('SILICONFLOW_API_KEY', '')

# ============================================================
# 工作流进度 Redis 持久化配置
# ============================================================
# 工作流进度默认使用 Redis db=2（db=0 给 Celery，db=1 给编排服务）
# 不可用时自动回退到进程内存（重启即丢失）
WORKFLOW_PROGRESS_REDIS_URL = os.getenv(
    'WORKFLOW_PROGRESS_REDIS_URL',
    'redis://localhost:6379/2'
)
# 进度数据 TTL（秒），超时自动清理，防止 Redis 内存泄漏
WORKFLOW_PROGRESS_TTL = int(os.getenv('WORKFLOW_PROGRESS_TTL', '3600'))

# ============================================================
# AI 编排服务（独立 FastAPI 服务）配置
# ============================================================
# Docker 内默认使用 http://ai-orchestrator:8001
# 本地开发默认回退到 http://localhost:8001
AI_ORCHESTRATION_SERVICE_URL = os.getenv(
    'AI_ORCHESTRATION_SERVICE_URL',
    'http://localhost:8001'
)

# AI 编排服务熔断器配置（保护 Django 不被挂掉的编排服务拖垮）
# 连续失败阈值，达到后熔断器打开，直接走本地回退
AI_ORCHESTRATION_CB_FAILURE_THRESHOLD = int(
    os.getenv('AI_ORCHESTRATION_CB_FAILURE_THRESHOLD', '5')
)
# 熔断后经过多少秒进入半开状态，允许一次试探请求
AI_ORCHESTRATION_CB_RECOVERY_TIMEOUT = int(
    os.getenv('AI_ORCHESTRATION_CB_RECOVERY_TIMEOUT', '60')
)
# 半开状态下允许的试探请求数
AI_ORCHESTRATION_CB_HALF_OPEN_MAX_CALLS = int(
    os.getenv('AI_ORCHESTRATION_CB_HALF_OPEN_MAX_CALLS', '1')
)
# 请求编排服务超时（连接秒, 读取秒）
AI_ORCHESTRATION_REQUEST_TIMEOUT = (
    int(os.getenv('AI_ORCHESTRATION_CONNECT_TIMEOUT', '10')),
    int(os.getenv('AI_ORCHESTRATION_READ_TIMEOUT', '300')),
)


DEFAULT_LLM_PROVIDER = os.getenv('DEFAULT_LLM_PROVIDER', 'deepseek')
DEFAULT_LLM_MODEL = os.getenv('DEFAULT_LLM_MODEL', 'deepseek-chat')

# ============================================================
# Midscene AI 配置 (视觉驱动 UI 自动化)
# ============================================================
MIDSCENE_AI_PROVIDER = os.getenv('MIDSCENE_AI_PROVIDER', 'qwen')
MIDSCENE_AI_MODEL = os.getenv('MIDSCENE_AI_MODEL', 'qwen-vl-max')
MIDSCENE_AI_API_KEY = os.getenv('MIDSCENE_AI_API_KEY', os.getenv('DASHSCOPE_API_KEY', ''))
# 注意：不要带 /v1 后缀，Midscene 会自行拼接 /v1/chat/completions
MIDSCENE_AI_BASE_URL = os.getenv('MIDSCENE_AI_BASE_URL', 'https://dashscope.aliyuncs.com/compatible-mode')

# ============================================================
# Milvus 向量数据库配置
# ============================================================
MILVUS_COLLECTION_NAME = os.getenv('MILVUS_COLLECTION_NAME', 'ai_test_knowledge')
# 默认使用 Milvus Lite 本地文件模式，数据保存在项目目录下，无需 Docker
# 如需连接远程 Milvus 服务器，可设置环境变量：MILVUS_URI=http://localhost:19530
MILVUS_URI = os.getenv('MILVUS_URI') or os.path.join(BASE_DIR, 'milvus_data', 'milvus.db')

# ============================================================
# 本地模型配置（隐私优先）
# ============================================================
# Embedding 模型: 本地 sentence-transformers 或 DashScope API
# USE_LOCAL_EMBEDDING=true → 使用 BAAI/bge-small-zh-v1.5（~130MB，无需 API Key）
# USE_LOCAL_EMBEDDING=false/未设 → 使用 DashScope text-embedding-v3（需 API Key）
USE_LOCAL_EMBEDDING = os.getenv('USE_LOCAL_EMBEDDING', 'false').lower() == 'true'
LOCAL_EMBEDDING_MODEL = os.getenv('LOCAL_EMBEDDING_MODEL', 'BAAI/bge-small-zh-v1.5')

# 本地 LLM: Ollama 接入
# OLLAMA_BASE_URL=http://localhost:11434/v1 （OpenAI 兼容接口）
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', '')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:7b')  # 支持 qwen2.5:7b, deepseek-r1:8b 等

# ============================================================
# Celery 异步任务配置
# ============================================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'  # 结果持久化到 Django DB
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 600  # 10 分钟超时

# Allure Report Directory
ALLURE_REPORT_DIR = BASE_DIR / 'allure-results'
ALLURE_REPORT_DIR.mkdir(exist_ok=True)

# ============================================================
# 结构化日志配置（W1.4：全链路追踪）
# ============================================================
# 日志格式：JSON 一行一条，包含 trace_id、timestamp、level 等
# 控制台：JSON（可读性好，方便 grep 和日志平台采集）
# 文件：JSON + 轮转（10MB × 5 份），路径：logs/
STRUCTURED_LOG_DIR = BASE_DIR / 'logs'
STRUCTURED_LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # --- JSON 结构化（生产首选）---
        'json': {
            '()': 'core.logging_setup.StructlogJSONFormatter',
        },
        # --- 纯文本控制台（开发时可切换）---
        'text': {
            'format': '{asctime} [{levelname}] {name} | trace_id={trace_id} | {message}',
            'style': '{',
        },
    },
    'filters': {
        'request_id': {
            '()': 'core.middleware.RequestIDLoggingFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'filters': ['request_id'],
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': STRUCTURED_LOG_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
            'filters': ['request_id'],
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': STRUCTURED_LOG_DIR / 'error.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'json',
            'filters': ['request_id'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        # 业务模块：捕获所有 core.* / agent_gateway / ai_evaluator 等
        'core': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'agent_gateway': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ai_evaluator': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'execution': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'data_factory': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# ============================================================
# 启动时注入 request_id filter
# ============================================================
# Django LOGGING dictConfig 对 filter 的处理仅在 handler 初始化时生效；
# root logger 和动态创建的 handler 可能遗漏 filter。
# 此处保底注入，确保 100% 的日志行都带 trace_id。
from core.logging_setup import inject_request_id_filter
inject_request_id_filter()

# ============================================================
# OpenTelemetry 全链路追踪初始化
# ============================================================
# 在 Django 启动时自动初始化 TracerProvider。
# 开发环境：Span 输出到控制台（ConsoleSpanExporter）。
# 生产环境：通过 OTEL_EXPORTER_OTLP_ENDPOINT 环境变量自动启用 OTLP 导出。
# 传播器：W3C TraceContext，与底座 FastAPI 默认兼容。
OTEL_ENABLED = os.getenv('OTEL_ENABLED', 'true').lower() == 'true'
if OTEL_ENABLED:
    try:
        from core.telemetry import setup_telemetry
        setup_telemetry()
    except ImportError as e:
        import logging
        logging.getLogger(__name__).warning(f"[OTel] 初始化失败（可忽略）: {e}")
